(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 240,
	height: 400,
	fps: 24,
	color: "#333333",
	opacity: 1.00,
	manifest: [
		{src:"images/blink.png?1478110298524", id:"blink"},
		{src:"images/build.png?1478110298524", id:"build"},
		{src:"images/city.jpg?1478110298524", id:"city"},
		{src:"images/cloud.png?1478110298524", id:"cloud"},
		{src:"images/tow1.png?1478110298524", id:"tow1"},
		{src:"images/tow2.png?1478110298524", id:"tow2"}
	]
};



lib.ssMetadata = [];


// symbols:



(lib.blink = function() {
	this.initialize(img.blink);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,389,395);


(lib.build = function() {
	this.initialize(img.build);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,320,554);


(lib.city = function() {
	this.initialize(img.city);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,500);


(lib.cloud = function() {
	this.initialize(img.cloud);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,607,187);


(lib.tow1 = function() {
	this.initialize(img.tow1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,67,393);


(lib.tow2 = function() {
	this.initialize(img.tow2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,67,269);


(lib.Символ42 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFDD57").s().p("A+AAFIAAgJMA8BAAAIAAAJg");
	this.shape.setTransform(192.2,0.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,384.3,1.1);


(lib.Символ41 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.Символ39 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#3366CC").s().p("AjNCFIAAgrIhdAAIAAArIgWAAIAAg/IAKgBQAEgDADgEIAFgNQADgIABgMIACgcIAEiDIBfAAIAADHIALAAIAABAgAkOADQAAAYgDAQQgDAPgGALIA/AAIAAixIguAAgAgaBOQgLgQAAgYIAAhsQAAgLACgMQACgLAGgJQAFgIALgGQAKgFAOAAQAQAAAKAFQAKAEAFAJQAGAIACALQABALAAAOIAABkQABAfgMAPQgMARgcgBQgaABgMgPgAgBhpQgEAFgDAGQgDAHAAAHIAAAMIAABqIABAKQAAAGADAFQADAEAEAEQAEADAIAAQAIAAAFgEQAFgCADgGQADgFABgGIABgNIAAhtIAAgMQgCgFgCgFQgDgFgFgEQgFgDgIAAQgLAAgDAEgAmsBOQgMgQAAgYIAAhsQAAgLADgMQACgLAFgJQAGgIAKgGQAKgFAQAAQAQAAALAFQAKAEAFAJQAFAIADALQABALAAAOIAABkQAAAfgMAPQgLARgdgBQgbABgMgPgAmThpQgFAFgCAGQgDAHgBAHIAAAMIAABqIABAKQAAAGAEAFQACAEAGAEQAEADAIAAQAJAAAEgEQAGgCACgGQAEgFABgGIABgNIAAhtIgBgMQgBgFgDgFQgCgFgFgEQgGgDgIAAQgKAAgFAEgAHbBaIAAjcIBgAAIAAAYIhGAAIAABJIA9AAIAAAYIg9AAIAABMIBGAAIAAAXgAFmBaIAAjcIBgAAIAAAYIhHAAIAABJIA+AAIAAAYIg+AAIAABMIBHAAIAAAXgAErBaIAAhkIgzAAIAABkIgaAAIAAjcIAaAAIAABhIAzAAIAAhhIAZAAIAADcgABfBaIAAjcIBaAAIAAAYIhBAAIAABBIATAAQARABAMAEQALAFAHAIQAGAKADALQABAKAAAOQAAAQgBANQgDAMgGAJQgHAJgLAEQgKAGgSgBgAB4BCIASAAQAMABAGgEQAHgDADgGQAEgGABgIIABgRIgBgQQgBgHgDgFQgEgFgHgEQgHgDgLAAIgSAAgAiiBaIAAjcIAuAAQARAAALAFQAKAEAHAIQAGAJADAMQADANAAAPQAAAOgDANQgCALgHAKQgGAJgMAFQgKADgTAAIgSAAIAABZgAiIgVIARAAQALAAAIgDQAGgEAEgGQAEgFABgIIABgQIgBgRQgBgIgEgGQgEgGgGgEQgHgCgMAAIgRAAgAnxBaIAAjEIgvAAIAADEIgaAAIAAjcIBjAAIAADcg");
	this.shape.setTransform(57.9,13);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0.8,-0.4,114.3,26.7);


(lib.Символ36 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#663300").s().p("AguBvIAAjdIBdAAIAAAYIhEAAIAABKIA7AAIAAAVIg7AAIAABPIBEAAIAAAXg");
	this.shape.setTransform(117.3,12.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#663300").s().p("AguBvIAAjdIBdAAIAAAYIhEAAIAABKIA7AAIAAAVIg7AAIAABPIBEAAIAAAXg");
	this.shape_1.setTransform(105.6,12.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#663300").s().p("AAZBvIAAhnIgxAAIAABnIgaAAIAAjdIAaAAIAABiIAxAAIAAhiIAaAAIAADdg");
	this.shape_2.setTransform(92.3,12.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#663300").s().p("AgxBvIAAjdIBYAAIAAAYIg/AAIAABCIASAAQAQAAAMAEQALAFAGAJQAHAHACALQACAMAAAOQAAAQgCANQgCAMgHAJQgGAJgLAFQgLAFgPAAgAgYBXIASAAQAJAAAHgEQAGgDAEgGQAEgGABgIIABgRIgBgQQgBgHgEgGQgEgGgGgDQgHgEgKAAIgRAAg");
	this.shape_3.setTransform(79.5,12.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#663300").s().p("AgmBiQgMgPAAgZIAAhsQAAgLACgMQACgLAGgJQAGgIAKgGQAKgFAOAAQAQAAAKAFQAKAEAGAJQAFAIACALQACALAAAOIAABlQAAAegMAQQgMAQgbAAQgaAAgMgPgAgNhUQgFAEgDAHQgCAGgBAHIAAAMIAABrIABAKQAAAFADAFQADAFAFADQAFADAHAAQAHAAAFgDQAFgDADgFQADgFABgHIABgNIAAhsIAAgMQgBgGgDgFQgCgFgGgEQgFgDgIAAQgIAAgFAFg");
	this.shape_4.setTransform(66.2,12.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#663300").s().p("AgyBvIAAjdIAuAAQAPAAALAFQAKAEAHAJQAGAIADAMQACANAAAPQAAAOgCANQgDAMgGAHQgGAJgMAFQgKAFgRAAIgSAAIAABagAgYgBIARAAQAJAAAIgDQAGgEAEgFQAEgGAAgIIACgQIgCgRQAAgIgEgGQgEgGgGgDQgHgDgJAAIgSAAg");
	this.shape_5.setTransform(53.7,12.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#663300").s().p("AAuCEIAAgrIhbAAIAAArIgWAAIAAg/IAJgBQAEgDAEgFIAFgMQADgHABgNIACgcIAEiDIBcAAIAADHIALAAIAABAgAgRACQAAAYgDAQQgDAQgHAKIA+AAIAAixIgtAAg");
	this.shape_6.setTransform(39.6,15.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#663300").s().p("AgmBiQgMgPAAgZIAAhsQAAgLACgMQACgLAGgJQAGgIAKgGQAKgFAOAAQAQAAAKAFQAKAEAGAJQAFAIACALQACALAAAOIAABlQAAAegMAQQgMAQgbAAQgaAAgMgPgAgNhUQgFAEgDAHQgCAGgBAHIAAAMIAABrIABAKQAAAFADAFQADAFAFADQAFADAHAAQAHAAAFgDQAFgDADgFQADgFABgHIABgNIAAhsIAAgMQgBgGgDgFQgCgFgGgEQgFgDgIAAQgIAAgFAFg");
	this.shape_7.setTransform(25.9,12.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#663300").s().p("AAYBvIAAjFIguAAIAADFIgaAAIAAjdIBhAAIAADdg");
	this.shape_8.setTransform(12.7,12.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(4,-6.4,120.6,39.1);


(lib.Символ35 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AmXDJIAAgTIgoAAIAAATIgJAAIAAgcIADAAIAEgDIACgGIACgIIAAgMIACg7IAqAAIAABYIAFAAIAAAcgAmzCQQAAALgBAHQgBAGgDAFIAcAAIAAhPIgVAAgAmLCyIAFgFIAFgGQACgEAAgGIABgPIAAg5IApAAIAABhIgLAAIAAhWIgUAAIAAAmIgBAWQAAAIgDAHQgCAFgEAEIgIAGgAJCCxQgFgHgBgKIAAgxIACgKQABgEACgFQADgDAEgCQAEgDAHAAQAIAAADADQAFABACAEQADAEAAAEIABALIAAAtQAAANgEAIQgGAGgMAAQgMABgFgHgAJMBhIgDAEIgBAGIAAAFIAAAwIAAAEIACAFIADADQACACAEgBQADABADgCIADgDIACgGIAAgGIAAgwIAAgFIgCgFQAAAAAAgBQAAAAgBgBQAAAAgBAAQAAgBgBAAQgCgCgEAAQgEAAgDADgABNCxQgFgHAAgKIAAgxIABgKQABgEACgFQADgDAEgCQAFgDAGAAQAIAAAEADQAEABADAEQACAEABAEIABALIAAAtQAAANgFAIQgGAGgMAAQgMABgFgHgABYBhIgEAEIgBAGIAAAFIAAAwIAAAEIACAFIAEADQACACADgBQAEABACgCIADgDIADgGIAAgGIAAgwIAAgFIgCgFQAAAAgBgBQAAAAAAgBQgBAAAAAAQgBgBgBAAQgCgCgEAAQgEAAgCADgAlCCxQgFgHAAgKIAAgxIABgKQABgEADgFQACgDAEgCQAEgDAIAAQAHAAAEADQAEABADAEQADAEAAAEIABALIAAAtQAAANgFAIQgFAGgMAAQgMABgGgHgAk3BhIgDAEIgBAGIgBAFIAAAwIABAEIACAFIACADQADACAEgBQADABACgCIAEgDIABgGIABgGIAAgwIgBgFIgBgFQAAAAgBgBQAAAAAAgBQgBAAAAAAQgBgBgBAAQgCgCgDAAQgFAAgCADgAIjC2IAAgtIgXAAIAAAtIgKAAIAAhhIAKAAIAAArIAXAAIAAgrIALAAIAABhgAHOC2IAAhhIAqAAIAAALIgfAAIAAAgIAbAAIAAAKIgbAAIAAAiIAfAAIAAAKgAG0C2IAAgpIgFABIgHABIgIgBQgEgBgDgDIgEgGQgCgFAAgGIAAgkIALAAIAAAkQAAAHADADQADADAGAAIAFAAIAFgCIAAgvIAMAAIAABhgAF8C2IAAhEIgBAAIgYBEIgLAAIAAhhIALAAIAABFIAAAAIAZhFIAKAAIAABhgAE+C2IAAgtIgWAAIAAAtIgLAAIAAhhIALAAIAAArIAWAAIAAgrIALAAIAABhgAEJC2IgEgVIgWAAIgEAVIgLAAIAUhhIALAAIAVBhgADxCXIASAAIgJguIAAAAgAC1C2IAAhhIAUAAQAHAAAFACQAEACADADQAEAFABAFIABAMIgBAMQgBAFgEAEQgCAEgFACQgFACgIABIgIAAIAAAmgADACFIAHAAQAFAAAEgBQADgCABgDQACgCAAgEIABgGIgBgIIgCgGQgBgDgDgBQgDgBgFAAIgIAAgACDC2IAAhhIAoAAIAAALIgdAAIAABWgAgEC2IAAhhIAoAAIAAALIgfAAIAAAgIAbAAIAAAKIgbAAIAAAiIAfAAIAAAKgAgdC2IAAhEIAAAAIgYBEIgLAAIAAhhIALAAIAABFIAAAAIAYhFIALAAIAABhgAhaC2IAAgtIgXAAIAAAtIgKAAIAAhhIAKAAIAAArIAXAAIAAgrIALAAIAABhgAivC2IAAhhIAqAAIAAALIgfAAIAAAgIAbAAIAAAKIgbAAIAAAiIAfAAIAAAKgAjDC2IgHgdQgBgFgCgDIgEgEIgEgDIgGAAIgEAAIAAAsIgLAAIAAgsIgFAAIgFAAIgFADQgCABgBADQgDADgBAFIgFAdIgMAAIAHgfQACgHADgFQADgFAFgCQgEgCgDgEQgDgFgCgHIgGgdIAKAAIAGAcQACAFACADIADAEIAFACIAEAAIAFAAIAAgqIALAAIAAAqIAEAAIAFAAIAEgCIAEgEQACgDABgFIAHgcIAKAAIgHAdQgBAHgDAFQgEAEgDACQAFACADAFQADAFABAHIAHAfgAn1C2IAAhhIAqAAIAAALIgfAAIAAAgIAaAAIAAAKIgaAAIAAAiIAfAAIAAAKgAosC2IAAhhIATAAQAIAAAEACQAFACADADQADAFABAFIABAMIgBAMQgBAFgDAEQgDAEgFACQgFACgHABIgJAAIAAAmgAoiCFIAIAAQAFAAADgBQADgCABgDQACgCAAgEIABgGIgBgIIgCgGQgBgDgDgBQgDgBgEAAIgJAAgApGC2IAAhWIgVAAIAABWIgMAAIAAhhIArAAIAABhgAhjA6IAAgTIgoAAIAAhfIALAAIAABVIAWAAIAAhVIALAAIAABVIAFAAIAAAdgApLAjIAGgFIAFgGQACgEABgGIAAgOIAAg4IApAAIAABfIgLAAIAAhUIgUAAIAAAmIAAAUQgCAJgCAFQgCAGgEAEIgIAGgAQWAiQgEgGAAgLIAAhJIALAAIAABJIAAAEIABAFIAEADQACABAEAAQADAAADgBIADgDIACgGIAAgFIAAhHIAMAAIAABFQgBANgFAIQgFAGgMAAQgMABgGgHgALJAiQgFgGgBgLIAAgvIACgKQABgEACgFQADgDAEgCQAEgDAHAAQAIAAADADQAFABACAEQADAEAAAEIABALIAAArQAAANgEAIQgGAGgMAAQgMABgFgHgALTgsIgDAEIgBAGIAAAGIAAAtIAAAEIACAFIADADQACABAEAAQADAAADgBIADgDIACgGIAAgFIAAgvIAAgFIgCgFQAAAAAAgBQAAAAgBgBQAAAAgBAAQAAgBgBAAQgCgCgEAAQgEAAgDADgADWAjQgGgHAAgLIAAgvIABgKIADgIQACgEAFgCQAEgDAHAAQAMAAAEAGQAGAHAAAKIgLABQAAgGgDgEQgDgDgFAAQgDAAgCABIgEAEIgCAFIAAAFIAAAwIAAAEIACAFIAEADIAEABQAGAAADgDQADgDAAgIIALACQgBAKgFAHQgFAFgLAAQgLAAgFgFgAoBAiQgFgGAAgLIAAgvIABgKQABgEADgFQACgDAEgCQAEgDAIAAQAHAAAEADQAFABACAEQACAEABAEIABALIAAArQAAANgFAIQgGAGgLAAQgMABgGgHgAn2gsIgEAEIgBAGIAAAGIAAAtIAAAEIADAFIADADQACABAEAAQADAAACgBIAEgDIACgGIAAgFIAAgvIAAgFIgCgFQAAAAgBgBQAAAAAAgBQgBAAAAAAQgBgBgBAAQgCgCgDAAQgEAAgDADgApzAjQgGgHAAgLIAAgvIABgKIADgIQADgEAEgCQAFgDAGAAQALAAAGAGQAEAHAAAKIgKABQgBgGgCgEQgCgDgGAAQgEAAgCABIgDAEIgBAFIgBAFIAAAwIABAEIABAFIADADIAGABQAFAAADgDQACgDABgIIALACQgBAKgFAHQgFAFgLAAQgLAAgFgFgAquAoIAAgIIAGAAQADAAACgDQADgDABgHIACgGIgVhFIALAAIAPA3IAAAAIANg3IAKAAIgTBJIgEANIgGAHIgEADIgGAAgAvLAiQgFgGAAgLIAAgvIABgKQABgEADgFQACgDAEgCQAEgDAIAAQAHAAAEADQAFABACAEQACAEABAEIABALIAAArQAAANgFAIQgFAGgMAAQgMABgGgHgAvAgsIgDAEIgCAGIAAAGIAAAtIAAAEIADAFIACADQADABAEAAQADAAACgBIAEgDIACgGIAAgFIAAgvIAAgFIgCgFQAAAAgBgBQAAAAAAgBQgBAAAAAAQgBgBgBAAQgCgCgDAAQgEAAgDADgAw4AjQgFgHgBgLIAAgvIABgKIADgIQADgEAEgCQAFgDAGAAQAMAAAFAGQAFAHAAAKIgLABQAAgGgDgEQgCgDgGAAQgDAAgCABIgEAEIgBAFIgBAFIAAAwIABAEIABAFIAEADIAFABQAFAAADgDQADgDAAgIIAMACQgBAKgGAHQgEAFgMAAQgKAAgGgFgAP7AnIgNgoIgLAAIAAAoIgLAAIAAhfIAWAAQALAAAGAHQAFAHAAAOQABAIgDAGQgCAHgIADIAOArgAPjgMIAJAAIAGgBIAFgDIACgGIAAgGIAAgHIgCgGIgFgDIgHgBIgIAAgAO9AnIAAgMIAMAAIAAAMgAOnAnIgPgoIgKAAIAAAoIgLAAIAAhfIAVAAQAMAAAGAHQAGAHAAAOQAAAIgDAGQgDAHgHADIAPArgAOOgMIAJAAIAHgBIADgDIACgGIABgGIgBgHIgCgGIgDgDIgHgBIgJAAgANQAnIAAhfIAqAAIAAALIgfAAIAAAgIAaAAIAAAKIgaAAIAAAgIAfAAIAAAKgAMsAnIgMhFIgOBFIgKAAIgOhfIAMAAIAIBDIABAAIALhDIALAAIAMBDIABAAIAIhDIALAAIgOBfgAKhAnIAAhVIgQAAIAAgKIAsAAIAAAKIgRAAIAABVgAJcAnIAAhfIAXAAQAJAAAFADQAFADACAHQABAGAAAJIAAAVIAAASQAAAIgBAGQgDAJgGADQgGACgHAAgAJnAdIAKAAQAIAAACgDQADgEAAgHIAAgvQAAgGgDgEQgCgEgIABIgKAAgAIpAnIAAhfIAqAAIAAALIgeAAIAAAgIAaAAIAAAKIgaAAIAAAgIAeAAIAAAKgAH3AnIAAhfIApAAIAAALIgeAAIAAAgIAaAAIAAAKIgaAAIAAAqgAGoAnIAAhfIAqAAIAAALIgfAAIAAAgIAaAAIAAAKIgaAAIAAAgIAfAAIAAAKgAGEAnIAAhVIgRAAIAAgKIAtAAIAAAKIgRAAIAABVgAFhAnIAAhCIAAAAIgZBCIgKAAIAAhfIAKAAIAABDIABAAIAYhDIALAAIAABfgAEqAnIgEgVIgWAAIgEAVIgLAAIAVhfIALAAIAUBfgAESAIIASAAIgJgsIAAAAgACiAnIgFgVIgVAAIgFAVIgLAAIAVhfIALAAIAUBfgACJAIIASAAIgJgsIAAAAgABkAnIAAgrIgXAAIAAArIgLAAIAAhfIALAAIAAArIAXAAIAAgrIAKAAIAABfgAANAnIAAhCIAAAAIgWBCIgLAAIAAhfIALAAIAABDIAAAAIAWhDIALAAIAABfgAgsAnIAAhCIgBAAIgYBCIgLAAIAAhfIALAAIAABDIAAAAIAZhDIAKAAIAABfgAifAnIgGgdQgBgFgCgDQgCgCgCAAIgEgDIgGAAIgFAAIAAAqIgLAAIAAhfIALAAIAAAqIAFAAIAFAAIAEgCIAEgEQACgDABgFIAHgcIAKAAIgHAdQgBAHgDAEQgDAFgFACQAGACADAFQADADABAHIAHAfgAjaAnIgEgVIgWAAIgFAVIgKAAIAUhfIALAAIAVBfgAjyAIIASAAIgJgsIAAAAgAkyAnIAAgpIgGAAIgFABIgEABIgDADIgDAIIgFAcIgMAAIAGgeIADgJQADgDADgDIgGgCIgDgGIgCgGIAAgHQgBgOAGgIQAGgHAMAAIAWAAIAABfgAlCgsIgFADIgCAHIgBAHQAAAPAOAAIAKAAIAAghIgJAAQgEAAgDABgAluAnIAAhCIAAAAIgZBCIgKAAIAAhfIAKAAIAABDIAAAAIAZhDIAKAAIAABfgAnLAnIAAhfIAVAAQAMAAAFAHQAGAGgBANQAAAHgCAFQgCAFgGADIAAABQAGABADAHQACADAAAJQAAAPgGAHQgGAGgNAAgAnAAdIAJAAQAEABADgCQADgCABgCIACgGIAAgJQAAgIgDgBQgCgFgJAAIgIAAgAnAgPIAIAAQAHAAAEgDQADgFAAgIQAAgHgDgEQgEgEgHAAIgIAAgArfAnIAAhCIgBAAIgZBCIgKAAIAAhfIAKAAIAABDIABAAIAZhDIAKAAIAABfgAs3AnIAAhCIgBAAIgYBCIgLAAIAAhfIALAAIAABDIAAAAIAZhDIAKAAIAABfgAtuAnIgGgdQgBgFgCgDQgCgCgCAAIgFgDIgEAAIgGAAIAAAqIgLAAIAAhfIALAAIAAAqIAFAAIAEAAIAFgCIAEgEQACgDABgFIAGgcIALAAIgHAdQgBAHgDAEQgEAFgEACQAGACADAFQADADACAHIAGAfgAwHAnIAAhfIAUAAQAHAAAGACQAEACADADQADAEABAGIABAMIgBALQgBAGgDAEQgCAEgFACQgGAAgIABIgIAAIAAAmgAv8gIIAIAAQAFAAADgBQADgCACgDQACgCAAgDIAAgHIAAgIIgCgGQgCgCgDgCQgDgBgFAAIgIAAgAFMg9QgEgCgCgCQgCgCgBgDIgBgGIAKAAIAAADIACADIADACIAEAAIADAAIADgCIADgDIAAgDIAJAAIgBAGIgEAFIgFAEQgEACgEAAQgGAAgDgCgAGMhTIAAgTIgoAAIAAhhIALAAIAABXIAWAAIAAhXIALAAIAABXIAFAAIAAAdgAC2hTIAAgTIgpAAIAAATIgKAAIAAgcIAFAAIADgDIACgGIACgIIABgNIABg6IAqAAIAABYIAEAAIAAAcgACaiMQgBALgBAGQgBAIgDAEIAbAAIAAhOIgUAAgAmWhrQgFgGAAgLIAAgwIABgLQABgEACgFQADgDAEgCQAFgDAGAAQAIAAAEADQAFABACAEQACADABAFIABALIAAAuQAAANgFAHQgGAGgMABQgLAAgGgHgAmLi7IgEAEIgBAGIAAAGIAAAvIAAAEIACAFIAEADQACABADAAQAEAAACgBIADgDIADgGIAAgFIAAgxIAAgFIgCgFQAAAAgBgBQAAAAAAgBQgBAAAAAAQgBgBgBAAQgCgCgEAAQgEAAgCADgAn/hmQgFgBgCgDQgDgDgCgEQgBgEAAgGIALgCQAAAIADADQACADAGAAIAEgBIAEgCIACgHIAAgJIAAgGQAAgDgBgDIgEgDQgCgCgDAAIgGAAIAAgKIAHAAQACAAACgBIAEgDIABgHIABgGIgBgIIgCgEQgBgBAAAAQgBgBAAAAQgBAAAAgBQAAAAgBAAIgEgBQgGAAgDAEQgCAEAAAGIgLgCQAAgKAGgGQAGgGAKAAQAEAAAFACQAEABADACQADADABAFQACAFAAAHIgBAGIgBAHIgCAFQgCAEgDABIAAAAIAFAEIADAGIABAHIAAAFQAAAPgFAHQgGAIgLAAQgGAAgDgCgAH+hmIAAgrIgGAAIgEABIgEACIgEAEIgDAIIgEAcIgMAAIAGgeIADgKQACgEAEgDIgGgCIgEgGIgBgGIgBgHQAAgOAFgIQAHgHALAAIAWAAIAABhgAHvi7IgFADIgCAGIgBAIQAAAPANAAIAKAAIAAghIgIAAQgFgBgCACgAHDhmIAAhEIgBAAIgZBEIgKAAIAAhhIAKAAIAABFIABAAIAZhFIAKAAIAABhgAFQhmIgEgVIgWAAIgEAVIgLAAIAVhhIAKAAIAVBhgAE3iFIASAAIgIguIgBAAgAD8hmIAAhhIAUAAQAHAAAFACQAEACADADQADAFACAFIABAMIgBALQgCAGgDAEQgCAEgFACQgFADgIgBIgIAAIAAAngAEHiXIAIAAQAFAAADgBQADgCABgDQACgCAAgDIABgHIgBgIIgCgGQgBgCgDgCQgDgCgFABIgIAAgADJhmIAAhhIAqAAIAAALIgfAAIAAAgIAaAAIAAAKIgaAAIAAAiIAfAAIAAAKgABXhmIAAhhIApAAIAAALIgeAAIAAAgIAbAAIAAAKIgbAAIAAAiIAeAAIAAAKgAAohmIAAgHQgFAAgEgCQgEgBgDgDQgDgDgCgEQgCgEAAgGIAAgmQAAgGACgEQACgFADgCQADgDAEgCQAEgBAFgBIAAgFIALAAIAAAFIAIACQAFACACADQAEACACAFQACAEAAAGIAAAmQAAAGgCAEQgCAEgEADQgDADgEABIgIACIAAAHgAAzh2QAFgBAEgEQADgDABgGIAAgmQgBgHgDgDQgEgDgFgBgAAfi0QgDADAAAHIAAAmQAAAGACADQADAEAHABIAAhCQgGABgDADgAghhmIAAgrIgGAAIgEABIgEACIgEAEIgCAIIgGAcIgLAAIAGgeIADgKQACgEAEgDIgGgCIgEgGIgCgGIAAgHQAAgOAGgIQAFgHANAAIAVAAIAABhgAgxi7IgEADIgCAGIgBAIQAAAPAOAAIAJAAIAAghIgIAAQgFgBgDACgAhehmIAAgtIgWAAIAAAtIgMAAIAAhhIAMAAIAAArIAWAAIAAgrIALAAIAABhgAjVhmIAAhhIAKAAIAABXIATAAIAAhXIALAAIAABXIAUAAIAAhXIALAAIAABhgAjphmIgFgVIgVAAIgFAVIgLAAIAVhhIALAAIAVBhgAkCiFIASAAIgJguIAAAAgAlFhmIAAhhIAoAAIAAALIgdAAIAAAcIAIAAQAIAAAFACQAFADADAEQADADAAAFIABALIgBANQAAAFgDAFQgDAEgFABQgFACgHAAgAk6hwIAIAAQAFAAADgCQADgBABgCIACgGIABgIIgBgHIgCgGQgBgCgDgCQgDgBgFgBIgIAAgAmuhmIgFgVIgVAAIgFAVIgKAAIAVhhIAKAAIAVBhgAnHiFIASAAIgIguIgBAAg");
	this.shape.setTransform(108.7,20.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,217.4,40.3);


(lib.Символ33 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.blink();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,389,395);


(lib.Символ30 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("EghvArCMAAAhWDMBDfAAAMAAABWDg");
	this.shape.setTransform(216,275.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,432,551);


(lib.Символ25 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(255,255,255,0.824)").s().p("AknBbIAMgKQAFgFAEgIQAEgIACgMQACgNAAgUIAAh4IBXAAIAADPIgYAAIAAi5IgqAAIAABSQAAAbgCATQgCASgFANQgEAMgIAHQgHAHgMAGgAAkBlQgIgDgHgGQgGgGgDgJQgEgIABgNIAXgEQAAARAGAGQAGAHAMAAQAFAAAEgCQAEgCAEgEQADgFACgIQACgIAAgMIgBgOQgBgHgDgFQgDgFgEgDQgFgDgGAAIgOAAIAAgSIAOAAQAHAAAEgDQAEgDADgFQADgFABgHIABgPQAAgKgCgGQgCgHgDgEQgEgDgEgCQgFgBgFAAQgMAAgGAIQgFAJAAANIgXgFQABgXANgMQANgMAUAAQALAAAJADQAIACAHAGQAGAHADAKQAEAKAAAQIgBANQAAAHgDAHQgCAGgDAGQgEAGgFADIAAABQAGADAEAEQADAFACAHQACAGABAHIAAAOQAAAegLAQQgMAQgZAAQgLAAgJgDgAhLBkQgIgEgGgGQgGgHgCgKQgDgJAAgLIAAgwIgYAAIAABhIgXAAIAAjPIAXAAIAABcIAYAAIAAgjQAAgLACgLQACgLAFgIQAFgIAJgFQAJgFAOAAQAPAAAJAFQAKAEAFAIQAEAHACALQACAKAAANIAABfQAAAbgLAQQgKAPgaAAQgMAAgJgEgAhDhRQgEAEgDAGQgCAGAAAHIAAALIAABkIAAAJQABAGADAEQACAFAEACQAFADAHAAQAHAAAFgDQAEgDADgEQACgFABgGIABgMIAAhmIAAgLQgBgGgCgEQgDgFgEgDQgFgDgIAAQgIAAgFAEgAn+BbQgMgOAAgYIAAhlQAAgLACgLQACgKAFgIQAFgJAKgFQAJgFAOAAQAZAAALANQALAOAAAVIgYAEQAAgOgFgIQgFgIgNAAQgHAAgFADQgEAEgDAFQgCAFgBAFIgBAMIAABnIABAKQABAFACAEQADAFAEADQAFADAHAAQALAAAGgHQAGgIAAgPIAYAEQAAAWgMANQgMANgXAAQgXAAgMgNgAr2BdQgMgLgCgUIAYgEQACAZAVAAQAHAAAFgDQAEgDADgFQACgFABgFIABgKIAAguIgwAAIAAgVIAwAAIAAgnQAAgOgFgIQgGgJgNAAQgLAAgGAIQgFAHgBALIgXgFQACgUALgLQAMgMAWAAQAQAAAJAFQAJAFAFAIQAFAIABAKQACAKAAAKIAABoQAAAYgMAOQgMANgXAAQgWAAgLgLgAKsBmIAAjPIBZAAIAAAWIhCAAIAABGIA5AAIAAAUIg5AAIAABJIBCAAIAAAWgAJzBmIAAjPIAYAAIAADPgAIDBmIAAjPIAYAAIAABUIARAAQARAAALAEQAKAFAGAIQAGAGACALQACALAAAOQAAAOgCAMQgCAMgGAIQgGAJgKAEQgKAFgQAAgAIbBPIARAAQAKAAAGgDQAHgDADgGQADgFABgIIABgQIgBgPQAAgHgEgFQgDgFgHgEQgGgCgLAAIgQAAgAHMBmIAAhhIgxAAIAABhIgXAAIAAjPIAXAAIAABcIAxAAIAAhcIAYAAIAADPgAEIBmIAAjPIAsAAQAbAAALAOQALAPAAAaQAAARgFAJQgFAKgMAHIAAABQAOAEAFALQAFANAAASQAAAhgOAOQgNAPgcAAgAEfBRIATAAQAKAAAGgEQAGgDADgGQADgGABgIIABgQQAAgRgHgJQgGgKgSAAIgSAAgAEfgRIAQAAQARAAAHgIQAHgJAAgQQAAgQgHgJQgHgIgQAAIgRAAgADSBmIAAiRIgBAAIg1CRIgWAAIAAjPIAXAAIAACSIABAAIA1iSIAWAAIAADPgAlBBmIgNg/QgDgLgDgGQgEgHgFgDQgEgEgFgBIgLgBIgMAAIAABgIgYAAIAAjPIAYAAIAABbIALAAIAJgBQAFgBAFgDQAEgDAEgGQAEgGADgLIAOg8IAWAAIgOA9QgDAPgHALQgHAKgIADQALAFAHAIQAGALADAQIAPBDgAozBmIgNg/QgDgLgDgGQgEgHgFgDQgEgEgFgBIgLgBIgMAAIAABgIgYAAIAAjPIAYAAIAABbIALAAIAJgBQAFgBAFgDQAEgDAEgGQAEgGADgLIAOg8IAWAAIgOA9QgDAPgHALQgHAKgIADQALAFAHAIQAGALADAQIAPBDg");
	this.shape.setTransform(86.2,9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(8.8,-1.8,154.8,21.7);


(lib.Символ24 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFDD57").s().p("Ap+BXIAMgJQAFgFAEgHQAEgIACgMQABgMAAgTIAAh1IBVAAIAADIIgXAAIAAiyIgpAAIAABPQAAAagCASQgCASgFAMQgEAMgHAHQgIAHgKAFgAGWBlIAAgSIAKAAQAHAAAFgHQAFgGAEgNIADgMIgsiSIAXAAIAeBvIABgBIAbhvIAWAAIgpCaQgEARgFAJQgFAKgFAFQgFAFgGABIgLACgAtKBlIAAgSIAKAAQAGAAAFgHQAGgGADgNIADgMIgriSIAWAAIAfBvIABgBIAbhvIAWAAIgpCaQgEARgFAJQgFAKgFAFQgGAFgFABIgLACgACxBXQgLgOAAgWIAAhiQAAgKACgLQACgKAFgIQAFgIAJgFQAJgEAPAAQAPAAAJAEQAJAEAFAIQAFAHACAKQABAKAAANIAABbQAAAbgKAPQgLAOgZAAQgZAAgLgNgADHhOQgEAEgCAGQgDAFAAAHIgBALIAABgIABAJQABAFADAFQACAEAFADQAEACAIAAQAHAAAEgCQAFgDADgFQACgEABgGIABgMIAAhiIAAgLQgBgFgDgFQgCgEgFgDQgEgEgIAAQgJAAgFAFgAnmBXQgLgOAAgWIAAhiQAAgKACgLQACgKAFgIQAFgIAJgFQAJgEAPAAQAPAAAJAEQAJAEAFAIQAFAHACAKQABAKAAANIAABbQAAAbgKAPQgLAOgZAAQgZAAgLgNgAnQhOQgEAEgCAGQgDAFAAAHIgBALIAABgIABAJQABAFADAFQACAEAFADQAEACAIAAQAHAAAEgCQAFgDADgFQACgEABgGIABgMIAAhiIAAgLQgBgFgDgFQgCgEgFgDQgEgEgIAAQgJAAgFAFgArTBXQgLgMAAgXIAAhiQAAgLACgKQACgLAEgIQAFgHAKgFQAIgFAOAAQAYAAAKAMQALANAAAVIgXAEQAAgNgFgIQgFgIgMAAQgHAAgEADQgFADgCAFQgDAFAAAGIgBALIAABjIABAKQAAAFADAEQACAEAFADQAEADAHAAQALAAAFgHQAGgHAAgPIAYAEQgBAWgLAMQgLAMgXAAQgWAAgMgNgAM/BiIAAiLIgBAAIgzCLIgVAAIAAjIIAWAAIAACNIABAAIAyiNIAWAAIAADIgALOBiIgNg9QgDgKgDgGQgEgGgEgEQgFgDgFgBIgKgBIgMAAIAABcIgXAAIAAjIIAXAAIAABYIAKAAIAKgBQAEAAAFgEQAEgDAEgFQAEgGACgKIAOg7IAVAAIgNA8QgDAOgHAKQgGAKgJAEQAMAEAGAIQAGAKADAPIAOBBgAJHBiIAAiyIgsAAIAACyIgXAAIAAjIIBaAAIAADIgAFyBiIgNg9QgDgKgDgGQgEgGgEgEQgFgDgFgBIgKgBIgMAAIAABcIgXAAIAAjIIAXAAIAABYIAKAAIAKgBQAEAAAFgEQAEgDAEgFQAEgGACgKIAOg7IAVAAIgNA8QgDAOgHAKQgGAKgJAEQAMAEAGAIQAGAKADAPIAOBBgABzBiIAAiyIgsAAIAACyIgXAAIAAjIIBaAAIAADIgAg7BiIAAhaIgMAAIgIABQgFABgEADQgEAEgEAGQgEAGgBAKIgLA7IgYAAIANg/QACgLAEgJQAEgJAJgFQgHgBgFgEQgFgEgDgGQgDgGgBgHIgBgPQAAgdAMgPQAMgQAZAAIAsAAIAADIgAhbhNQgGADgDAFQgDAFgCAHQgBAHAAAIQAAAgAcAAIATAAIAAhGIgSAAQgIAAgGADgAi2BiIAAiLIgBAAIgzCLIgWAAIAAjIIAWAAIAACNIABAAIAziNIAWAAIAADIgAl3BiIAAjIIArAAQAaAAAKAOQALAOAAAaQAAAQgEAJQgFAKgMAGIAAABQANAEAFALQAFAMAAASQAAAfgNAOQgNAOgbAAgAlgBOIASAAQAKAAAFgEQAGgDADgGQADgFABgIIABgPQAAgRgGgJQgGgJgSAAIgRAAgAlggQIAPAAQAQAAAHgIQAHgJAAgQQAAgPgHgJQgGgIgQAAIgQAAg");
	this.shape.setTransform(85.4,7.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-3,170.8,21);


(lib.Символ23 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFDD57").s().p("AG5BkQgHgDgGgFQgGgEgDgIQgEgHAAgKIAAh9QAAgJAEgIQADgHAGgFQAGgFAHgDQAHgCAJAAQARAAAMAKQAMAKgBATIAAB9QAAAKgDAHQgDAIgGAEQgFAFgIADQgIACgHAAQgJAAgHgCgAG7hLQgEAFAAAHIAAB/QAAAIAEAEQAGAFAIAAQAHAAAFgFQAGgEAAgIIAAh/QAAgHgGgFQgFgFgHAAQgIAAgGAFgAFLBkQgIgDgFgFQgFgEgEgIQgDgHgBgKIAAglQABgLAEgIQAEgHAIgEQgIgEgEgIQgEgIgBgLIAAgbQABgJADgIQAEgHAFgFQAFgFAIgDQAHgCAJAAQAHAAAIACQAHADAGAFQAGAFADAHQAEAIgBAJIAAAbQABALgFAIQgFAIgGAEQAGAEAFAHQAFAIgBALIAAAlQABAKgEAHQgDAIgGAEQgGAFgHADQgIACgHAAQgJAAgHgCgAFNAJQgEAFAAAHIAAAsQAAAIAEAEQAGAEAIAAQAHAAAFgEQAFgEABgIIAAgsQgBgHgFgFQgFgFgHAAQgIAAgGAFgAFNhMQgEAFAAAHIAAAhQAAAIAEAFQAGAEAIAAQAHAAAFgEQAFgFABgIIAAghQgBgHgFgFQgFgEgHAAQgIAAgGAEgAQZBkIAAiKIgCAAIglBZIgLAAIglhZIgBAAIAACKIgXAAIAAjIIAXAAIAsBvIAAAAIArhvIAXAAIAADIgAM6BkIAAgaIAZAAIAAAagALCBkIAAjIIAqAAQAaAAALAOQALAOAAAaQAAAQgFAJQgEAKgMAGIAAABQANAEAFALQAEAMABASQAAAfgNAOQgNAOgbAAgALZBQIASAAQAJAAAGgEQAGgDADgGQADgFABgIIAAgPQAAgRgFgJQgHgJgRAAIgRAAgALZgOIAPAAQAQAAAHgIQAHgJAAgQQAAgPgHgJQgHgIgPAAIgQAAgAKZBkIgNg9QgCgKgEgGQgEgGgEgEQgFgDgFgBIgKgBIgMAAIAABcIgXAAIAAjIIAXAAIAABYIALAAIAJgBQAFAAAEgEQAFgDAEgFQADgGACgKIAPg7IAUAAIgNA8QgDAOgGAKQgHAKgJAEQAMACAGAKQAGAKADAPIAPBBgADEBkIAAjIIAWAAIAADIgABXBkIAAjIIAXAAIAABSIAQAAQARAAAKAEQALAEAFAIQAGAGADALQABAKAAANQAAAOgBAMQgDALgGAIQgGAJgJAEQgKAEgQAAgABuBOIAQAAQALAAAFgDQAHgDADgFQADgFABgIIABgPIAAgPQgCgGgDgGQgDgFgHgDQgGgDgKAAIgQAAgAAOBkIAAizIggAAIAAgVIBZAAIAAAVIgiAAIAACzgAg7BkIAAhdIgvAAIAABdIgWAAIAAjIIAWAAIAABZIAvAAIAAhZIAXAAIAADIgAjqBkIAAjIIBWAAIAAAWIhAAAIAABDIA4AAIAAATIg4AAIAABHIBAAAIAAAVgAkgBkIAAiKIgBAAIglBZIgLAAIglhZIgBAAIAACKIgXAAIAAjIIAXAAIArBvIAAAAIAshvIAXAAIAADIgAm3BkIgKgtIgsAAIgJAtIgWAAIAqjIIAWAAIAsDIgAnpAiIAlAAIgShcIgBAAgApABkIAAizIgiAAIAAgVIBcAAIAAAVIgiAAIAACzgArGBkIAAjIIApAAQAQAAAJAFQAKAEAGAHQAFAIADALQACALAAAPQAAAMgCALQgCALgGAHQgGAIgKAEQgKAFgRAAIgQAAIAABRgAqvAAIAPAAQALAAAGgEQAGgDADgFQAEgFABgHIABgPIgBgPQgBgHgEgGQgCgFgHgDQgGgDgKAAIgQAAgArvBkIgKgtIgsAAIgJAtIgWAAIArjIIAVAAIAsDIgAshAiIAlAAIgShcIgBAAgAtuBkIAAiyIgrAAIAACyIgYAAIAAjIIBaAAIAADIgAvaBkIgJgtIgtAAIgJAtIgWAAIArjIIAVAAIAsDIgAwMAiIAlAAIgRhcIgCAAg");
	this.shape.setTransform(107.2,7.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-3,214.4,20.6);


(lib.Символ22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag3B5IAAgnIhUAAIAAAnIgUAAIAAg6IAJgBQADgCADgFQADgDACgIQADgGAAgLIACgaIAEh3IBVAAIAAC0IALAAIAAA7gAhxADQgBAWgDAOQgCAOgGAJIA6AAIAAigIgrAAgAgHBGQgLgNAAgXIAAhhQABgKACgLQACgKAEgIQAFgIAHgFQAKgFAOABQAPAAAJADQAKAFAFAIQAEAHACAKQABAKABAMIAABcQAAAbgLAPQgLAOgZAAQgZAAgJgOgAANheQgEADgCAHQgCAFgBAHIgBAKIAABgIABAKQABAFADAEQACAFAFACQAFADAHAAQAHAAAFgDQAEgCADgFQACgFABgGIABgLIAAhiIAAgLQgBgGgCgEQgDgFgFgDQgEgDgIAAQgJAAgFAFgAGBBSIAAjIIBXAAIAAAVIhAAAIAABEIA3AAIAAAVIg3AAIAABFIBAAAIAAAVgAFKBSIAAjIIAXAAIAADIgADdBSIAAjIIAYAAIAABRIAQAAQARAAAKAEQAKAFAGAIQAGAIACALQACAIAAANQAAAOgCALQgCAMgGAIQgGAJgJAEQgLAEgPAAgAD1A8IAQAAQAKAAAGgDQAGgDADgFQAEgGABgHIABgPIgBgPQgBgGgEgEQgDgFgGgDQgHgDgJAAIgQAAgABnBSIAAjIIAqAAQAaAAALAOQALAOAAAaQgBAQgEAJQgEAKgMAGIAAABQAMAEAGAMQAEALAAASQAAAfgMAOQgNAOgcAAgAB+A9IASAAQAJAAAFgDQAGgDADgGQAEgGABgHIAAgPQAAgSgGgGQgGgJgSAAIgQAAgAB+ghIAOAAQAQAAAIgHQAGgJABgQQgBgQgGgIQgHgIgQAAIgPAAgAjGBSIAAiLIgBAAIgyCLIgWAAIAAjIIAWAAIAACNIABAAIAyiNIAXAAIAADIgAmGBSIAAjIIArAAQAaAAAKAOQALAOAAAaQAAAQgEAJQgFAKgMAGIAAABQANAEAFAMQAFALgBASQAAAfgMAOQgNAOgcAAgAlvA9IASAAQAJAAAGgDQAFgDADgGQAEgGABgHIABgPQAAgSgHgGQgFgJgTAAIgQAAgAlvghIAPAAQAQAAAHgHQAHgJAAgQQAAgQgHgIQgGgIgRAAIgPAAgAnXBSIAAgVIAFAAIAAAVgAnXhhIAAgVIAFAAIAAAVg");
	this.shape.setTransform(98.6,10.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(51.4,-2,94.4,24.2);


(lib.Символ21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F6F6F6").s().p("AIwBZQgLgOAAgWIAAhiQAAgKACgLQACgKAFgIQAFgIAKgFQAIgEAPAAQAPAAAKAEQAJAEAFAIQAEAHACAKQABAKAAANIAABbQABAbgLAPQgLAOgZAAQgZAAgLgNgAJHhMQgFAEgCAGQgDAFAAAHIAAALIAABgIABAJQAAAFADAFQADAEAEADQAFACAHAAQAHAAAFgCQAFgDACgFQADgEABgGIABgMIAAhiIgBgLQgBgFgDgFQgCgEgEgDQgFgEgIAAQgJAAgEAFgAE9BZQgKgOAAgWIAAhiQAAgKACgLQACgKAFgIQAFgIAJgFQAJgEAOAAQAPAAAKAEQAJAEAFAIQAEAHACAKQACAKAAANIAABbQAAAbgLAPQgKAOgaAAQgZAAgLgNgAFUhMQgFAEgCAGQgCAFAAAHIgBALIAABgIABAJQAAAFADAFQADAEAFADQAEACAHAAQAIAAAEgCQAFgDACgFQADgEABgGIABgMIAAhiIAAgLQgCgFgCgFQgCgEgFgDQgEgEgJAAQgIAAgFAFgADPBZQgLgMAAgXIAAhiQAAgLABgKQADgLAEgIQAFgHAJgFQAJgFAOAAQAXAAALAMQALANAAAVIgXAEQAAgNgFgIQgFgIgMAAQgHAAgEADQgFADgCAFQgDAFgBAGIgBALIAABjIABAKQABAFADAEQACAEAFADQADADAIAAQALAAAFgHQAGgHAAgPIAYAEQgBAWgLAMQgLAMgXAAQgXAAgLgNgAllBZQgKgOgBgWIAAhiQABgKABgLQADgKAFgIQAEgIAKgFQAIgEAPAAQAPAAAKAEQAJAEAEAIQAFAHACAKQABAKAAANIAABbQAAAbgKAPQgLAOgZAAQgZAAgLgNgAlOhMQgFAEgCAGQgDAFAAAHIAAALIAABgIABAJQAAAFADAFQADAEAEADQAFACAHAAQAHAAAEgCQAGgDACgFQADgEABgGIABgMIAAhiIgBgLQgBgFgDgFQgCgEgEgDQgFgEgIAAQgJAAgEAFgArqBZQgLgMAAgXIAAhiQAAgLACgKQACgLAFgIQAEgHAKgFQAIgFAPAAQAXAAALAMQAKANABAVIgYAEQAAgNgEgIQgGgIgLAAQgIAAgEADQgEADgCAFQgDAFgBAGIgBALIAABjIABAKQABAFADAEQACAEAEADQAEADAHAAQALAAAGgHQAFgHAAgPIAYAEQgBAWgLAMQgLAMgWAAQgXAAgMgNgAKgBkIAAjIIBWAAIAAAWIhAAAIAABDIA3AAIAAATIg3AAIAABHIBAAAIAAAVgAH/BkIgOg9QgCgKgDgGQgEgGgEgEQgGgDgEgBIgKgBIgNAAIAABcIgWAAIAAjIIAWAAIAABYIALAAIAJgBQAFAAAEgEQAFgDAEgFQAEgGACgKIAOg7IAVAAIgOA8QgDAOgGAKQgHAKgIAEQALACAHAKQAFAKAEAPIAOBBgACPBkIAAjIIAWAAIAADIgAAiBkIAAjIIAXAAIAABSIAQAAQARAAAKAEQALAEAGAIQAFAGADALQABAKAAANQAAAOgBAMQgDALgFAIQgHAJgJAEQgKAEgQAAgAA5BOIAQAAQALAAAFgDQAHgDADgFQADgFABgIIABgPIAAgPQgCgGgDgGQgDgFgHgDQgGgDgKAAIgQAAgAhTBkIAAjIIAqAAQAaAAALAOQAJAOAAAaQAAAQgFAJQgCAKgMAGIAAABQANAEADALQAEAMABASQAAAfgLAOQgNAOgbAAgAg8BQIASAAQAJAAAGgEQAGgDADgGQADgFABgIIAAgPQAAgRgFgJQgHgJgSAAIgQAAgAg8gOIAPAAQAQAAAHgIQAHgJAAgQQAAgPgHgJQgHgIgPAAIgQAAgAj1BkIAAjIIBWAAIAAAWIhAAAIAABDIA3AAIAAATIg3AAIAABHIBAAAIAAAVgAmjBkIAAiKIgCAAIglBZIgKAAIglhZIgBAAIAACKIgXAAIAAjIIAXAAIArBvIAAAAIArhvIAYAAIAADIgAo6BkIgKgtIgsAAIgJAtIgWAAIArjIIAVAAIArDIgApsAiIAlAAIgShcIgBAAg");
	this.shape.setTransform(79.2,17.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(3.4,7.5,151.7,20.6);


(lib.Символ20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFDD57").s().p("ApUB4IAAgmIhUAAIAAAmIgVAAIAAg4IAJgCQAEgCADgEQADgEACgHQACgIABgKIACgZIADh4IBWAAIAAC1IAKAAIAAA5gAqPADQAAAVgDAPQgCAOgGAKIA5AAIAAihIgqAAgAHsBHQgKgOAAgWIAAhiQAAgLACgKQACgKAFgIQAFgIAJgFQAJgEAOgBQAPAAAKAFQAJADAFAIQAEAIACAKQACAKAAAMIAABcQAAAagLAPQgLAPgZAAQgZAAgLgNgAIDhfQgFAFgCAFQgCAGgBAHIAAALIAABgIABAJQAAAFADAFQADADAEADQAFADAHAAQAHAAAFgDQAFgDACgEQADgEABgHIABgMIAAhhIgBgLQgBgFgCgFQgCgEgFgDQgFgEgIAAQgIAAgFAEgAsOBRQgJgCgGgGQgGgGgDgJQgDgIAAgMIAXgFQAAASAGAGQAFAFAMABIAJgCQAEgCADgEQADgEACgIQACgIAAgMIgBgNQgBgHgDgDQgDgFgEgCQgEgEgGAAIgNAAIAAgUIANAAQAGABAEgDQAFgDACgFQADgFABgGIABgPQAAgJgCgHQgCgFgDgFQgDgDgFgBQgEgCgFAAQgMAAgFAIQgFAKAAAMIgXgGQABgVANgMQAMgMATAAQALABAJACQAIACAGAGQAHAGADAKQADAKAAAQIgBALQAAAIgCAGQgCAHgEAFQgDAGgGACIAAABQAHAEADAFQAEAGACAGIACALIAAANQAAAdgLAPQgLAQgZAAQgKAAgIgDgALUBSIAAjIIBWAAIAAAWIhAAAIAABDIA4AAIAAAVIg4AAIAABFIBAAAIAAAVgAKeBSIAAiyIgrAAIAACyIgXAAIAAjIIBZAAIAADIgAFxBSIAAjIIApAAQAQAAAKAFQAJADAGAIQAGAHACAMQACALAAAOQAAANgCALQgCALgGAJQgFAHgLAFQgKADgQAAIgRAAIAABRgAGIgTIAQAAQAKAAAGgDQAHgDADgGQADgFABgGIABgPIgBgQQgBgGgDgGQgDgGgGgDQgHgCgKAAIgQAAgAD5BSIAAjIIArAAQAaAAAKAOQALAOAAAZQAAARgEAJQgFAJgMAHIAAABQANAEAFANQAFAKAAARQAAAggNAOQgNAOgbAAgAEQA+IASAAQAKAAAFgEQAGgDADgGQADgGABgHIABgQQAAgRgGgGQgGgKgSAAIgRAAgAEQggIAPAAQAQAAAHgJQAHgIAAgQQAAgPgHgJQgGgIgQAAIgQAAgACPBSIAAjIIBXAAIAAAWIhAAAIAABDIA3AAIAAAVIg3AAIAABFIBAAAIAAAVgAgfBSIAAjIIAoAAQAaAAALAOQALAOAAAZQAAARgFAJQgEAJgMAHIAAABQANAEAFANQAEAKAAARQAAAggMAOQgNAOgcAAgAgIA+IAQAAQAJAAAGgEQAFgDADgGQAEgGABgHIAAgQQAAgRgGgGQgGgKgSAAIgOAAgAgIggIANAAQAQAAAHgJQAHgIAAgQQAAgPgHgJQgHgIgQAAIgNAAgAjCBSIAAjIIBXAAIAAAWIhAAAIAABDIA3AAIAAAVIg3AAIAABFIBAAAIAAAVgAj2BSIAAiMIgBAAIgzCMIgVAAIAAjIIAWAAIAACNIABAAIAyiNIAWAAIAADIgAl1BSIAAhbIguAAIAABbIgXAAIAAjIIAXAAIAABZIAuAAIAAhZIAXAAIAADIgAnjBSIgKgtIgsAAIgJAtIgWAAIAqjIIAWAAIArDIgAoWAPIAmAAIgShbIgCAAg");
	this.shape.setTransform(83.4,14.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(2.4,2.5,162.1,24.2);


(lib.Символ16 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.tow2();
	this.instance.setTransform(0,-1,0.174,0.166);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-1,11.7,44.7);


(lib.Символ15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.tow1();
	this.instance.setTransform(0,0,0.162,0.162);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,10.8,63.8);


(lib.Символ14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhNAdQgEgGAAgIIAAgdQAAgJAEgFQAFgEAHAAQAHAAAEAEQAFAFAAAJIAAAdQAAAJgFAFQgEAEgHAAQgGAAgGgEgAhHgWQgCADAAAEIAAAgQAAADACADQACACAEAAQADAAADgCQACgCAAgEIAAggQAAgFgCgCQgCgCgEAAQgEAAgCACgAgcAcQgDgEAAgHIAAggQAAgJAEgEQAEgDAGAAQAIAAADADQAEAEAAAHIAAADIgHAAIAAgDIgBgEQgEgDgCAAQgEAAgCACQgCAEAAADIAAAfQAAAEACACQABADAEAAQAEAAACgDQACgCAAgEIAAgBIAIAAIAAACQAAAHgEAEQgEAEgIAAQgIAAgDgEgAAjAfIgHgcIgJAAIAAAcIgIAAIAAg8IAIAAIAAAbIAGAAQAAAAABAAQABAAAAgBQABAAAAAAQABgBAAAAIACgJIABgGQABgHACgCQADgDAFAAIABAAIAAAHIgBAAQAAAAAAAAQgBAAAAABQAAAAgBAAQAAAAAAABQgCABAAAGIgCAHIAAAGIgDACIAKAfgACEAfIgEgOIgMAAIgDAOIgIAAIAOg9IAGAAIAOA9gACAAKIgFgXIgCAAIgFAXIAMAAgAA/AfIAAg9IANAAQAIAAAEADQAEAEAAAIIAAABQAAAHgEAEIgCABIACACQAEADAAAIIAAACQAAAKgEAEQgEAEgIAAgABHAYIADAAQAFAAADgCQADgCAAgGIAAgFQAAgEgCgCQgDgDgEAAIgFAAgABHgFIAFAAQAEAAADgCQACgCAAgDIAAgFQAAgEgDgCQgDgCgFAAIgDAAgAhoAeIAAgmIgCAAIgKAbIgDAAIgKgbIgCAAIAAAmIgHAAIAAg8IAHAAIAOAjIAAgCIAMghIAIAAIAAA8g");
	this.shape.setTransform(14,3.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,28,6.7);


(lib.Символ13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACEAuIAAgJIgmAAIAAhRQAAgGAFAAQAFAAAAAGIAABIIATAAIAAhIQAAgGAGAAQAFAAAAAGIAABIIAHAAIAAASQAAAFgEAAQgFAAAAgFgAhSAuIAAgJIglAAIAAAJQAAAFgFAAQgEAAAAgFIAAgSIAFAAIABgBQAFgLACgLQACgUAAgdIAAgGIAhAAIAABOIAHAAIAAASQAAAFgEAAQgFAAAAgFgAhnggQAAAYgEARQgBAJgEAJIgBABIAWAAIAAhFIgMAAgADcAlQgFgBABgGIAMghIgBgBQgEAAgCgEQgEgFAAgIIAAgHQAAgKAFgFQAFgHAPAAIAQAAIAABSQAAAFgFAAQgFAAAAgFIAAghIgLAAIgLAiQgBAEgDAAIgCAAgADmgmQgDAEAAAFIAAAHQAAAGADADQAEADAFAAIAJAAIAAgfIgJAAQgGAAgDADgABJAhIgEgQIgTAAIgDAQQgCAFgEgBQgEgBAAgFIAShNQABgEAEAAQAEAAABAEIASBNQAAAFgEABIgCAAQgDAAgBgEgABFAJIgJgtIgJAtIASAAgAC9AgIAAg3IgYAyIAAAFQAAAFgFAAQgFAAAAgFIAAhMQAAgGAFAAQAEAAAAAGIAAA3IAZgzIAAgEQAAgGAFAAQAFAAAAAGIAABMQAAAFgFAAQgFAAAAgFgAgGAgIAAhSIANAAQAQAAAFAHQAEAFAAAKIAAAGQAAAKgEAEQgFAHgQAAIgFAAIAAAhQAAAFgDAAQgFAAAAgFgAACgKIAIAAQAGAAADgCQAEgEAAgGIAAgHQAAgGgEgDQgCgDgHAAIgIAAgAg4AlIAAhXIAfAAQAEAAAAAFQAAAFgEAAIgWAAIAAAeIATAAQAEAAAAAEQAAAEgEAAIgTAAIAAAdIAWAAQAFAAAAAFQAAAFgFAAgAivAlIAAhXIAfAAQAFAAAAAFQAAAFgFAAIgVAAIAAAeIASAAQAFAAAAAEQAAAEgFAAIgSAAIAAAdIAWAAQAEAAAAAFQAAAFgEAAgAjlAgIAAgIIgGAAQgLAAgGgGQgFgHAAgLIAAgOQAAgNAGgHQAGgFAMAAIAEAAIAAgFQAAgGAFAAQAFAAAAAGIAAAFIAFAAQALAAAGAFQAGAHAAANIAAAOQAAALgFAHQgGAGgLAAIgGAAIAAAIQAAAFgFAAQgFAAAAgFgAjbAPIAFAAQAHAAAEgEQACgDAAgGIAAgSQAAgIgEgEQgDgCgHAAIgEAAgAjzgcQgEAEAAAIIAAASQAAAGADADQADAEAHAAIAFAAIAAgtIgDAAQgIAAgDACg");
	this.shape.setTransform(25.8,5.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,51.7,10.3);


(lib.Символ12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AByAsQgFgBACgGIALgiIAAgBIgBgBQgDAAgDgCQgEgGAAgHIAAgHQAAgIAFgHQAFgHAPAAIAQAAIAABSQAAAFgEAAQgFAAAAgFIAAgjIgLAAIgLAkQgBAEgEAAIgCAAgAB9gfQgEADAAAGIAAAHQAAAGAEADQADADAGAAIAJAAIAAgfIgJAAQgHAAgCADgAg8AoIgDgQIgUAAIgDAQQgBAFgFgBQgEgBAAgFIARhNQADgEADAAQAEAAABAEIASBNQAAAFgEABIgCAAQgDAAgBgEgAhAAQIgJgtIgJAtIASAAgABQAnIAAgkIgXAAIAAAkQAAAFgFAAQgFAAAAgFIAAhMQAAgGAFAAQAFAAAAAGIAAAiIAXAAIAAgiQAAgGAFAAQAFAAAAAGIAABMQAAAFgFAAQgFAAAAgFgAgjAsIAAhRQAAgGAFAAQAFAAAAAGIAABIIARAAIAAhIQAAgGAFAAQADAAAAAGIAABIIASAAIAAhIQAAgGAFAAQAFAAAAAGIAABRgAiXAsIAAhXIAgAAQAEAAAAAFQAAAFgEAAIgXAAIAAAbIAJAAQAMAAAFAFQAFADAAAJIAAALQAAAHgEAGQgFAJgNAAgAiOAjIAIAAQAHAAADgFQADgDAAgHIAAgFQAAgIgEgDQgDgDgFAAIgJAAg");
	this.shape.setTransform(15.3,4.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,30.6,8.9);


(lib.Символ5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.cloud();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,607,187);


(lib.Символ51 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ14();
	this.instance.setTransform(16,3.8,1.144,1.144,0,0,0,14,3.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,32,7.6);


(lib.Символ50 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ13();
	this.instance.setTransform(69.3,5.9,1.144,1.144,0,0,0,25.9,5.1);

	this.instance_1 = new lib.Символ12();
	this.instance_1.setTransform(17.5,5.1,1.144,1.144,0,0,0,15.3,4.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,98.8,11.7);


(lib.Символ40 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ30();
	this.instance.setTransform(595,193.5,1,1,0,0,0,216,275.4);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:0},5).to({_off:true},1).wait(698).to({_off:false},0).to({alpha:1},15).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(379,-81.9,432,551);


(lib.Символ38 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ42();
	this.instance.setTransform(189.5,0.1,1,1,0,0,0,192.2,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(0,0,0,0.824)","rgba(0,0,0,0.498)","rgba(0,0,0,0.824)"],[0.145,0.478,0.816],-162.5,0,162.6,0).s().p("A5YHlIAAvJMAyxAAAIAAPJg");
	this.shape.setTransform(186.6,48.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-2.7,-0.4,384.3,97.6);


(lib.Символ37 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ36();
	this.instance.setTransform(99.8,31.2,1,1,0,0,0,64.3,13.3);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFDD57").s().rr(-144.4,-39,288.8,78,15.9);
	this.shape.setTransform(99.8,31.2,0.8,0.8);

	this.instance_1 = new lib.Символ39();
	this.instance_1.setTransform(97.3,32.3,1,1,0,0,0,55.4,11.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().rr(-144.4,-39,288.8,78,15.9);
	this.shape_1.setTransform(99.8,31.2,0.8,0.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape},{t:this.instance}]}).to({state:[{t:this.shape_1},{t:this.instance_1}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-15.7,0,231,62.4);


(lib.Символ34 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ35();
	this.instance.setTransform(105.1,-112.2,1,1,0,0,0,108.7,20.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-3.6,-132.4,217.4,40.3);


(lib.Символ32 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("EgE3ArbQgMl4gEl5QgFnvganoQgcoRAqoOQAmnOgJnWIhuAAIgcgVIAJgDIAlzRQCQkuE+kZQBPBRArBzQA+E7AkHZUACoAwfAALAOTIpFFuIAADJg");
	var mask_graphics_35 = new cjs.Graphics().p("EgE3ArbQgMl4gEl5QgFnvganoQgcoRAqoOQAmnOgJnWIhuAAIgcgVIAJgDIAlzRQCQkuE+kZQBPBRArBzQA+E7AkHZUACoAwfAALAOTIpFFuIAADJg");
	var mask_graphics_135 = new cjs.Graphics().p("EgE3ArbQgMl4gEl5QgFnvganoQgcoRAqoOQAmnOgJnWIhuAAIgcgVIAJgDIAlzRQCQkuE+kZQBPBRArBzQA+E7AkHZUACoAwfAALAOTIpFFuIAADJg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:45.4,y:278.5}).wait(35).to({graphics:mask_graphics_35,x:45.4,y:278.5}).wait(100).to({graphics:mask_graphics_135,x:45.4,y:278.5}).wait(1));

	// Слой 2
	this.instance = new lib.Символ33();
	this.instance.setTransform(185.5,494.8,0.382,1.224,35,0,0,194.7,197.6);
	this.instance.alpha = 0.328;
	this.instance.compositeOperation = "lighter";

	this.instance.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(35).to({x:-62.5,y:55.3},100).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,254.1,90.8,302.9);


(lib.Символ31 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("Ao3cxQBL4pDf6bQC+krH5iSIAbAWIBvAAQAIHWglHNQgrIQAdIQQAaHoAEHuQAFF5ALF5g");
	var mask_graphics_99 = new cjs.Graphics().p("Ao3cxQBL4pDf6bQC+krH5iSIAbAWIBvAAQAIHWglHNQgrIQAdIQQAaHoAEHuQAFF5ALF5g");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:56.8,y:187.4}).wait(99).to({graphics:mask_graphics_99,x:56.8,y:187.4}).wait(1));

	// Слой 2
	this.instance = new lib.Символ33();
	this.instance.setTransform(147.1,470.8,0.382,1.224,35,0,0,194.7,197.6);
	this.instance.alpha = 0.328;
	this.instance.compositeOperation = "lighter";

	this.instance.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:-12.5,y:-42.4},99).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,230.1,113.6,144.6);


(lib.Символ27 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ37();
	this.instance.setTransform(96,39.1,0.792,0.792,0,0,0,96,31.3);
	new cjs.ButtonHelper(this.instance, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(7.6,14.3,182.9,49.4);


(lib.Символ26 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ34();
	this.instance.setTransform(96.2,420.2,1,1,0,0,0,102.2,23.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(510).to({y:90.2,alpha:0},0).to({alpha:1},20,cjs.Ease.get(1)).wait(177).to({y:100.2,alpha:0},10,cjs.Ease.get(-1)).wait(3));

	// Слой 1
	this.instance_1 = new lib.Символ27();
	this.instance_1.setTransform(96,351.2,1,1,0,0,0,96,31.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(510).to({y:31.2,alpha:0},0).to({y:21.2,alpha:1},20,cjs.Ease.get(1)).wait(179).to({y:31.2,alpha:0},10,cjs.Ease.get(-1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-9.6,263.8,217.4,119.9);


(lib.Символ17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ32();
	this.instance.setTransform(210.9,283.7,1,1,0,0,0,45.4,278.5);

	this.instance_1 = new lib.Символ31();
	this.instance_1.setTransform(122.9,374.3,1,1,0,0,0,56.8,187.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

	// Слой 1
	this.instance_2 = new lib.build();

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,550.4,898.1);


(lib.Символ10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.city();
	this.instance.setTransform(10,-60,1.178,0.844);

	this.instance_1 = new lib.city();
	this.instance_1.setTransform(10,768.1,1.177,0.814,0,180,0);

	this.instance_2 = new lib.Символ41();
	this.instance_2.setTransform(-163.4,88.9,0.737,1.73,-90,0,0,251.2,153.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(10,-60,353.3,828.1);


(lib.Символ8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ16();
	this.instance.setTransform(6.3,48,1.144,1.144,0,0,0,5.5,21.9);

	this.instance_1 = new lib.Символ15();
	this.instance_1.setTransform(21.6,36.5,1.144,1.144,0,0,0,5.5,31.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,27.6,72.9);


(lib.Символ7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ5();
	this.instance.setTransform(303.5,93.5,1,1,0,0,0,303.5,93.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,607,187);


(lib.Символ3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Символ 24
	this.instance = new lib.Символ24();
	this.instance.setTransform(131.1,75.9,1,1,0,0,0,85.4,10.5);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(354).to({_off:false},0).to({y:65.9,alpha:1},14,cjs.Ease.get(1)).wait(116).to({y:55.9,alpha:0},15,cjs.Ease.get(-1)).to({_off:true},206).wait(15));

	// Символ 25
	this.instance_1 = new lib.Символ25();
	this.instance_1.setTransform(131.1,45.9,1,1,0,0,0,84.9,12);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(348).to({_off:false},0).to({regX:0,regY:0,x:46.2,y:23.9,alpha:1},14,cjs.Ease.get(1)).wait(116).to({regX:84.9,regY:12,x:131.1,y:35.9},0).to({y:25.9,alpha:0},15,cjs.Ease.get(-1)).to({_off:true},212).wait(15));

	// Символ 23
	this.instance_2 = new lib.Символ23();
	this.instance_2.setTransform(128,75.9,1,1,0,0,0,107.2,10.3);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(223).to({_off:false},0).to({y:65.9,alpha:1},14,cjs.Ease.get(1)).wait(88).to({y:55.9,alpha:0},15,cjs.Ease.get(-1)).to({_off:true},1).wait(379));

	// Символ 22
	this.instance_3 = new lib.Символ22();
	this.instance_3.setTransform(131,46,1,1,0,0,0,99.4,12.1);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(214).to({_off:false},0).to({y:36,alpha:1},14,cjs.Ease.get(1)).wait(88).to({y:26,alpha:0},15,cjs.Ease.get(-1)).to({_off:true},1).wait(388));

	// Символ 21
	this.instance_4 = new lib.Символ21();
	this.instance_4.setTransform(130.6,42.3,1,1,0,0,0,78.8,17.9);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(51).to({_off:false},0).to({y:32.3,alpha:1},14,cjs.Ease.get(1)).wait(113).to({y:22.3,alpha:0},15,cjs.Ease.get(-1)).wait(527));

	// Символ 20
	this.instance_5 = new lib.Символ20();
	this.instance_5.setTransform(131.1,76,1,1,0,0,0,83.5,17.9);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(58).to({_off:false},0).to({y:66,alpha:1},14,cjs.Ease.get(1)).wait(113).to({y:56,alpha:0},15,cjs.Ease.get(-1)).wait(520));

	// Слой 1
	this.instance_6 = new lib.Символ38();
	this.instance_6.setTransform(159.5,201.5,1,1,0,0,0,203.5,50.5);
	this.instance_6.alpha = 0.41;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(28).to({y:61.5,alpha:1},23,cjs.Ease.get(1)).wait(669));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-46.7,150.6,384.3,97.5);


(lib.Символ52 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ8();
	this.instance.setTransform(49,32,1.108,1.108,0,0,0,13.8,36.5);

	this.instance_1 = new lib.Символ50();
	this.instance_1.setTransform(48.9,86,1.108,1.108,0,0,0,49.4,5.9);

	this.instance_2 = new lib.Символ51();
	this.instance_2.setTransform(49.1,100.6,1.108,1.108,0,0,0,16,3.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-5.9,-8.4,109.4,113.2);


(lib.Символ18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ17();
	this.instance.setTransform(160,277,1,1,0,0,0,160,277);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,550.4,898.1);


(lib.Символ11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Символ 16
	this.instance = new lib.Символ52();
	this.instance.setTransform(253.7,25.1,1,1,0,0,0,49.4,51.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(198.4,-34.4,109.4,113.2);


(lib.Символ9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ7();
	this.instance.setTransform(910.5,93.5,1,1,0,0,0,303.5,93.5);

	this.instance_1 = new lib.Символ7();
	this.instance_1.setTransform(303.5,93.5,1,1,0,0,0,303.5,93.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,1214,187);


(lib.Символ6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ9();
	this.instance.setTransform(607,93.5,1,1,0,0,0,607,93.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:1.1},399).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,1214,187);


(lib.Символ2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Символ 17
	this.instance = new lib.Символ18();
	this.instance.setTransform(536,251.4,1.37,1.37,0,0,0,160.1,276.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:1.25,scaleY:1.25,x:537.3,y:392.7},59,cjs.Ease.get(-1)).to({regY:277,scaleX:1.14,scaleY:1.14,x:538.7,y:538.2},59,cjs.Ease.get(1)).wait(1).to({regY:277.1,y:538.3},0).to({regY:277,scaleX:0.88,scaleY:0.88,x:551.2,y:473.8},60,cjs.Ease.get(-1)).to({regX:160.2,regY:277.2,scaleX:0.72,scaleY:0.72,x:563.5,y:433.6},69,cjs.Ease.get(1)).wait(171).to({scaleX:1.2,scaleY:1.2,x:620.6,y:735.4},70,cjs.Ease.get(-1)).to({regX:160.3,regY:277.3,scaleX:1.63,scaleY:1.63,x:673.1,y:1012.8},60,cjs.Ease.get(1)).wait(171));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(316.7,-127.9,753.8,1230.2);


(lib.Символ1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Символ 6
	this.instance = new lib.Символ6();
	this.instance.setTransform(693.5,124.5,1,1,0,0,0,303.5,93.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(159).to({regX:303.6,scaleX:1.04,scaleY:1.04,x:699.6,y:130},39,cjs.Ease.get(-1)).to({regX:303.5,scaleX:1.09,scaleY:1.09,x:705.8,y:137.6},41,cjs.Ease.get(1)).wait(160).to({regX:303.6,scaleX:1.14,scaleY:1.14,x:710.8,y:51.1},49,cjs.Ease.get(-1)).to({regX:303.5,scaleX:1.19,scaleY:1.19,x:715.6,y:-17.7},50,cjs.Ease.get(1)).wait(222));

	// Символ 10
	this.instance_1 = new lib.Символ10();
	this.instance_1.setTransform(590,300.2,1,1.5,0,0,0,200,200.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(159).to({regX:200.1,scaleX:1.04,scaleY:1.55,x:591.8,y:283.2},39,cjs.Ease.get(-1)).to({regX:200,regY:200,scaleX:1.09,scaleY:1.6,x:593.5,y:265.3},41,cjs.Ease.get(1)).wait(160).to({regX:200.1,scaleX:1.14,scaleY:1.67,x:592.9,y:181.1},49,cjs.Ease.get(-1)).to({scaleX:1.19,scaleY:1.76,x:592.2,y:114.9},50,cjs.Ease.get(1)).wait(1).to({regX:200.2,scaleX:1.3,scaleY:1.91,x:594.3,y:121},220).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-38.2,-90,1642.3,1242.1);


(lib.Символ19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ11();
	this.instance.setTransform(-149.1,45.9,0.832,0.832,0,0,0,43.2,44.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-19.9,-19.9,91.1,94.1);


(lib.Символ4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ19();
	this.instance.setTransform(-19,47.1,1,1,0,0,0,-19,47.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(119).to({x:489,y:147.1,alpha:0},0).to({x:491,y:151.1,alpha:1},30,cjs.Ease.get(1)).wait(330).to({scaleX:1.07,scaleY:1.07,x:519.4,y:155.8},20,cjs.Ease.get(-1)).to({regX:-18.9,scaleX:1.14,scaleY:1.14,x:549.3,y:160.7},21,cjs.Ease.get(1)).wait(189).to({alpha:0},10).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-19.9,-19.9,91.1,94.1);


// stage content:



(lib.Federacia_light_240400 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 6
	this.instance = new lib.Символ40();
	this.instance.setTransform(-435,-10.9,1,1,0,0,0,38,26);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 5
	this.instance_1 = new lib.Символ26();
	this.instance_1.setTransform(118,364.9,1,1,0,0,0,96,31.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// Символ 4
	this.instance_2 = new lib.Символ4();
	this.instance_2.setTransform(-498.4,-24,1,1,0,0,0,-19,47.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

	// Символ 3
	this.instance_3 = new lib.Символ3();
	this.instance_3.setTransform(193.5,361.5,1,1,0,0,0,203.5,50.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(1));

	// Символ 2
	this.instance_4 = new lib.Символ2();
	this.instance_4.setTransform(-85.5,53,1,1,0,0,0,356.5,277);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(1));

	// Слой 1
	this.instance_5 = new lib.Символ1();
	this.instance_5.setTransform(-71.9,203.3,0.717,0.717,0,0,0,303.5,200);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-379.4,-151.9,1359.4,1237.4);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;