(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 300,
	height: 300,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/dom_cat300_300_atlas_.png?1471091213183", id:"dom_cat300_300_atlas_"}
	]
};



lib.ssMetadata = [
		{name:"dom_cat300_300_atlas_", frames: [[242,378,159,146],[193,620,42,58],[242,526,159,93],[136,620,55,56],[0,378,240,240],[0,620,134,60],[136,678,50,48],[0,0,416,376]]}
];


// symbols:



(lib.cat_cut_02 = function() {
	this.spriteSheet = ss["dom_cat300_300_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.cat_cut_04 = function() {
	this.spriteSheet = ss["dom_cat300_300_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.cat_cut_07 = function() {
	this.spriteSheet = ss["dom_cat300_300_atlas_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.cat_cut_08 = function() {
	this.spriteSheet = ss["dom_cat300_300_atlas_"];
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.city = function() {
	this.spriteSheet = ss["dom_cat300_300_atlas_"];
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();



(lib.logo = function() {
	this.spriteSheet = ss["dom_cat300_300_atlas_"];
	this.gotoAndStop(5);
}).prototype = p = new cjs.Sprite();



(lib.pattern = function() {
	this.spriteSheet = ss["dom_cat300_300_atlas_"];
	this.gotoAndStop(6);
}).prototype = p = new cjs.Sprite();



(lib.wall = function() {
	this.spriteSheet = ss["dom_cat300_300_atlas_"];
	this.gotoAndStop(7);
}).prototype = p = new cjs.Sprite();



(lib.Символ22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E94D33").s().p("AilBiQAAgBgCgGQgDgFAAgJQABgMAHgIQAJgIALAAQANAAAIAIQAIAIAAAMQAAAGgEAJQgDAIgIAGIgsAggAD6BbQgMgOAAgTQAAgNAFgLQAFgLALgHQAMgHAPAAQAXAAANAOQANAOAAASQAAAMgGALQgGALgLAIQgLAHgQAAQgXABgMgOgAESArQgGAFAAAJQAAAKAGAEQAFAEAHAAQAHAAAGgEQAFgEAAgKQAAgJgFgFQgGgDgHAAQgHAAgFADgAgrBkQgQgGgNgHIgMgGIAQglIAJAFQAKAFAMAEQANADANAAQARAAAKgKQALgKAAgOQAAgOgLgJQgKgJgQABIghAAIAAgXIAshAIhDAAIAAgrICEAAIAAAWIgxBEQAWAGAPARQAQASAAAgQAAAagOASQgOAQgTAIQgTAHgOAAQgQAAgRgEgACDBmICIjsIAvAAIiGDsgAkwBmIAxhQQgWgBgSgLQgRgKgLgQQgLgRAAgWQABgWAKgTQAMgTATgLQATgLAWAAQAXAAATALQATALALATQALATAAAWQAAAKgEAMIgIAUIgFAKIhCBpgAkThPQgJAJABAPQgBAQAJAJQAJAIAPAAQAPAAAJgIQAJgJAAgQQAAgPgJgJQgJgJgPABQgPgBgJAJgAB7g3QgMgNAAgVQAAgMAFgLQAGgLALgHQALgHAPAAQARAAALAHQALAHAGALQAGALAAAMQAAAMgGALQgGALgMAHQgLAIgQAAQgYgBgMgOgACThmQgGADAAAKQAAAKAGAEQAFAEAHAAQAHAAAFgEQAGgEAAgKQAAgKgGgDQgFgFgHAAQgGAAgGAFg");
	this.shape.setTransform(206.4,25.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AkPBqQgZgOgPgcQgPgbgBglQABgjAPgcQAPgcAZgPQAagOAfAAQAfAAAaAOQAaAPAPAcQAPAcAAAjQAAAlgPAbQgPAcgaAOQgaAPgfAAQgfAAgagPgAj1hDQgOAKgIASQgIARAAAWQAAAXAIASQAHASAPAJQAOAKARAAQARAAAOgKQAPgJAIgSQAIgSAAgXQAAgWgIgRQgIgSgPgKQgOgKgRAAQgRAAgOAKgAHDB3IhThoIAABnIgzAAIAAjrIAzAAIAABiIBThiIA8AAIhlBzIBmB5gALQB2IgRgzQgZAKgSAAQgSAAgZgKIgRAzIg2AAIBXjrIA3AAIBWDrgAJ3AZQAOAIAPAAQAOAAAPgIIgdhYgAB8B2IAAjrICYAAIAAArIhlAAIAAA2IBLAAIAAAqIhLAAIAAA1IBpAAIAAArgAgSB2IAAjAIg/AAIAAgrICvAAIAAArIg/AAIAADAgAmYB2IAAjAIhSAAIAADAIgzAAIAAjrIC5AAIAADrgAp4B2IAAiUIhaCUIgzAAIAAjrIAzAAIAACWIBaiWIAzAAIAADrg");
	this.shape_1.setTransform(81.5,24);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(4.1,11.8,235.9,27.7);


(lib.Символ20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E94D33").s().p("ABvBRIAAgcIhYAAIAAAcIgXAAIAAg0IANAAIAGgJQAFgHAGgUQAFgVAAgZIAAgZIBXAAIAABrIANAAIAAA0gAA2AAQgHATgDAFIgDAFIA0AAIAAhSIghAAQAAAjgGASgAhpAvQgOgJgIgPQgJgPAAgUQAAgUAJgQQAIgPAOgIQAPgJARABQASgBAOAJQAPAIAIAPQAIAQAAAUQAAAUgIAPQgIAPgPAJQgOAIgSAAQgRAAgPgIgAhagyQgIAGgEAKQgFAKAAAMQAAAMAEAKQAFAKAIAFQAIAFAJAAQAKAAAIgFQAIgFAEgKQAFgKAAgMQAAgMgFgKQgEgKgIgGQgIgFgKAAQgJAAgIAFgAHVA1IAAiDIBVAAIAAAZIg5AAIAAAeIAqAAIAAAXIgqAAIAAAcIA7AAIAAAZgAGiA1Igjg4IAAA4IgdAAIAAg4IgjA4IgiAAIAwhDIgwhAIAiAAIAjA3IAAg3IAdAAIAAA3IAig3IAjAAIgwBAIAwBDgADzA1IgJgdQgOAFgKAAQgKAAgOgEIgJAcIgfAAIAxiDIAeAAIAxCDgADCABQAIAEAIAAQAIAAAIgEIgQgwgAj3A1IAAiDIA5AAQAMAAAJAFQAKAFAFAJQAFAJAAALQAAAMgFAJQgFAJgKAFQgJAEgMAAIgdAAIAAA1gAjbgXIAcAAQAIgBAEgEQAFgFAAgGQAAgGgFgFQgEgDgIAAIgcAAgAkrA1IAAhqIgtAAIAABqIgdAAIAAiDIBnAAIAACDgAorA1IAAiDIA3AAQAOAAAJAFQAKAFAEAIQAEAIAAAJQAAAJgEAJQgEAIgGACQAJADAGAIQAFAHAAALQAAAKgEAKQgFAIgKAFQgKAGgQAAgAoOAcIAcAAQAIAAAEgDQAFgFAAgHQAAgGgFgFQgEgDgIABIgcAAgAoOgYIAYgBQAHAAAEgEQAEgEAAgGQAAgHgEgEQgEgDgHAAIgYAAg");
	this.shape.setTransform(227.2,15.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AJJA8QgOgJgIgPQgJgPAAgVQAAgTAJgQQAIgQAPgHQAOgJARABQAOAAANAEQAMAGAIAKIgYAOQgLgLgMAAQgJAAgIAGQgIAFgEALQgFAKAAALQAAAMAFALQAEAKAIAFQAIAFAJAAQAMAAALgKIAYAOQgIAKgMAFQgNAGgOAAQgRAAgPgIgAG0A8IALgWQAHADAEAAQAEAAADgCQAEgEAEgIIgrhcIAeAAIAbA/IAcg/IAeAAIgrBdQgIATgLALQgLAKgNAAQgMAAgLgIgABOA8QgOgJgIgPQgJgPAAgVQAAgTAJgQQAIgPAOgIQAPgJARABQASgBAOAJQAPAIAIAPQAIAQAAATQAAAVgIAPQgIAPgPAJQgOAIgSAAQgRAAgPgIgABdglQgIAGgEAKQgFAKAAALQAAAMAEALQAFAKAIAFQAIAFAJAAQAKAAAIgFQAIgFAEgKQAFgLAAgMQAAgLgFgKQgEgKgIgGQgIgFgKAAQgJAAgIAFgAqIA8QgOgJgIgPQgJgPAAgVQAAgTAJgQQAIgPAOgIQAPgJARABQASgBAOAJQAPAIAIAPQAIAQAAATQAAAVgIAPQgIAPgPAJQgOAIgSAAQgRAAgPgIgAp5glQgIAGgEAKQgFAKAAALQAAAMAEALQAFAKAIAFQAIAFAJAAQAKAAAIgFQAIgFAEgKQAFgLAAgMQAAgLgFgKQgEgKgIgGQgIgFgKAAQgJAAgIAFgAMEBCIgJgdQgOAFgKAAQgKAAgOgEIgJAcIgfAAIAxiDIAeAAIAxCDgALTAOQAIAEAIAAQAIAAAIgEIgQgwgAF+BCIAAhqIgtAAIAABqIgdAAIAAiDIBnAAIAACDgAC/BCIAAiDIA5AAQAMAAAJAFQAKAFAFAJQAFAJAAALQAAAMgFAJQgFAHgKAFQgJAFgMAAIgdAAIAAA2gADbgKIAcAAQAIgBAEgEQAFgFAAgGQAAgGgFgFQgEgDgIAAIgcAAgAgEBCIgug6IAAA6IgdAAIAAiDIAdAAIAAA3IAug3IAgAAIg2BAIA2BDgAj4BCIAAiDIBVAAIAAAZIg4AAIAAAeIAqAAIAAAWIgqAAIAAAdIA6AAIAAAZgAkrBCIAAiDIAcAAIAACDgAmeBCIAAiDIAcAAIAAAzIAcAAQALAAAKAEQALADAHAHQAHAJAAAOQAAAOgIAKQgIAKgLAEQgKAFgJAAgAmCApIAaAAQANAAADgGQADgHAAgFQAAgEgDgFQgEgGgMAAIgaAAgAoXBCIAAiDIA2AAQAOAAAKAFQAJAFAFAIQAEAIAAAJQAAAJgEAJQgEAIgHACQAKACAFAHQAGAJAAALQAAAKgFAKQgEAIgLAFQgKAGgPAAgAn7ApIAdAAQAHAAAFgDQAEgFAAgHQAAgGgEgFQgFgFgHABIgdAAgAn7gLIAZgBQAHAAADgEQAEgEAAgGQAAgHgEgEQgEgDgGAAIgZAAgArUBCIAAg2IgxAAIAAA2IgdAAIAAiDIAdAAIAAA3IAxAAIAAg3IAcAAIAACDg");
	this.shape_1.setTransform(83.5,14.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(3.2,7.5,279.7,16.2);


(lib.Символ19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACNBJQgNgJgGgQQgIgQAAgWQAAgUAIgRQAGgQANgIQANgJARAAQASAAANAJQANAIAHAQQAHARAAAUQAAAWgHAQQgHAQgNAJQgNAIgSAAQgRAAgNgIgACZghQgIAGgEAMQgDALAAAOQAAAPADAMQAEALAIAHQAJAHAJgBQARAAAJgOQAJgOAAgXQAAgVgJgPQgJgOgRAAQgJgBgJAIgAADBJQgLgJgHgQQgHgQAAgWQAAgUAHgRQAHgQALgIQANgJARAAQARAAANAJQANAIAIAQQAGARAAAUQAAAWgGAQQgIAQgNAJQgNAIgRAAQgRAAgNgIgAAPghQgIAGgEAMQgDALAAAOQAAAPADAMQAEALAIAHQAIAHAKgBQAQAAAKgOQAJgOAAgXQAAgVgJgPQgKgOgQAAQgKgBgIAIgAiGBJQgMgJgIgQQgGgQgBgWQABgUAGgRQAIgQAMgIQANgJASAAQARAAANAJQANAIAHAQQAHARAAAUQAAAWgHAQQgHAQgNAJQgNAIgRAAQgSAAgNgIgAh5ghQgIAGgFAMQgDALAAAOQAAAPADAMQAFALAIAHQAHAHALgBQAPAAAKgOQAJgOAAgXQAAgVgJgPQgKgOgPAAQgLgBgHAIgAlBBMQgLgFgGgJQgIgJgBgMIAYAAQACAKAHAFQAIAGAJgBQALAAAHgGQAHgIAAgLQAAgMgHgIQgHgGgLAAQgHAAgHADQgHAEgEAGIgTgLIAAhGIBUAAIAAATIg9AAIAAAnQAFgDAHgCQAGgCAIgBQAMABAKAEQAJAEAHALQAFAKABAOQAAANgGAKQgFAKgMAGQgLAGgQAAQgMAAgLgFgArJBKQgLgHgGgMQgGgMAAgOQAAgOAGgMQAGgKALgHQAMgHAPAAQAOAAAMAHQALAHAGAKQAGAMAAAOQAAAOgGANQgGAMgLAGQgMAHgOAAQgPAAgMgHgArDAEQgIAKAAAPQAAAPAIAJQAHAKAOAAQANAAAHgKQAHgJAAgPQAAgPgHgKQgHgHgNAAQgOAAgHAHgAJ9BPIAAhaIgdBDIgRAAIgdhEIAABbIgYAAIAAiJIAYAAIAmBVIAlhVIAYAAIAACJgAG0BPIA5iTIAWAAIg5CTgAE9BPIAAgaIgLAAIAAgUIALAAIAAhbIA4AAQANAAAJAEQAKAGAFAJQAGAJAAALQAAAMgGAHQgFAKgKAEQgJAFgNABIghAAIAAANIAXAAIAAAUIgXAAIAAAagAFUAAIAhAAQAKAAAGgEQAFgGAAgJQAAgIgFgGQgGgGgKAAIghAAgAm0BPIAegyIgIABQgLAAgKgGQgLgFgGgJQgHgKAAgMQAAgOAHgLQAFgLAMgGQALgHANABQANgBALAHQALAGAGALQAGALABAOQgBAGgCAGQgCAHgDAFIgqBDgAmtgfQgHAHAAAMQAAALAGAFQAHAGALAAQAMAAAGgHQAIgEgBgLQABgMgIgHQgGgIgMAAQgKAAgHAIgApSBPIAAhQIgfAAIAAgTIBUAAIAAATIgfAAIAABQgAKoAKIAAgGIAcghIAKgQQADgFABgFQgBgFgEgEQgDgDgGAAQgGAAgDADQgEAEAAAFQAAAJAFADIgIALQgFgEgEgFQgDgFAAgIQABgIADgGQAEgGAGgDQAGgDAIAAQAIAAAGADQAGADAEAGQADAGAAAIQAAALgJAMIgXAeIAiAAIAAALg");
	this.shape.setTransform(76.4,13.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(2.6,5.8,147.5,16.3);


(lib.Символ17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#330000").s().p("AgDAoIAAgSQgLgBgGgGQgGgGAAgJQAAgJAGgGQAGgGALgBIAAgRIAHAAIAAARQALABAGAGQAGAGAAAJQAAAJgGAGQgGAGgLABIAAASgAAEANQAGgBAEgEQAEgDAAgFQAAgFgEgEQgDgDgHgBgAgNgJQgDAEAAAFQAAAFADADQAEAEAGABIAAgaQgGAAgEAEg");
	this.shape.setTransform(94,129.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#330000").s().p("AgTAgIAAg+IAJAAIAAAFQADgDADgBQAEgCACAAQAFAAAEADQAFADACAFQACAFAAAHQAAAHgCADQgCAGgEADQgFADgFAAQgCAAgEgCIgGgEIAAAYgAgIgSQgDAEAAAGQAAAHADACQAEAFAEAAQAFAAADgFQADgCAAgGQAAgHgDgEQgEgFgEAAQgEAAgEAFg");
	this.shape_1.setTransform(88.6,130);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#330000").s().p("AgDAEQAAAAAAgBQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAAAAAAAQAAAAAAgBQAAAAABgBQAAAAAAgBQABAAAAgBQABAAAAAAQABAAAAAAQAAgBAAAAQAAAAABABQABAAAAAAQABAAAAAAQABABAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAAAAAAAQAAAAAAABQAAAAAAABQAAAAAAABQgBABAAAAQgBAAAAABQgBAAAAAAQgBAAAAAAQgBABAAAAQAAAAAAgBQAAAAgBAAQAAAAgBAAQAAgBgBAAg");
	this.shape_2.setTransform(85,130.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#330000").s().p("AAJAfIAAgeIgQAeIgKAAIAAgsIAKAAIAAAcIAQgcIAJAAIAAAsgAgGgVQgDgCgCgFIAGgCIACAEIADABIADgBQABgBAAAAQAAAAABgBQAAAAAAgBQAAAAAAgBIAGACQgBAFgEACQgDACgDAAQgDAAgDgCg");
	this.shape_3.setTransform(81.6,128.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#330000").s().p("AAIAWIAAgcIgQAcIgJAAIAAgrIAJAAIAAAbIAQgbIAKAAIAAArg");
	this.shape_4.setTransform(76.8,129.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#330000").s().p("AAIAWIAAgSIgPAAIAAASIgJAAIAAgrIAJAAIAAASIAPAAIAAgSIAKAAIAAArg");
	this.shape_5.setTransform(72.1,129.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#330000").s().p("AgZAWIAAgrIAJAAIAAAjIAMAAIAAgjIAIAAIAAAjIANAAIAAgjIAJAAIAAArg");
	this.shape_6.setTransform(66.5,129.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#330000").s().p("AgKAVQgEgBgCgEQgCgDABgDQgBgIAGgCQAFgDAFgBIALAAQAAgKgJAAIgEABIgEAFIgHgEQACgEAFgDQAFgDAEAAQAFAAAEACQAEACACAEQACAFAAAGIAAAZIgHAAIgBgEQgHAFgFAAQgEAAgEgCgAgDACQgFACAAAFQABADACACQACACADAAQADAAADgDQADgCAAgEIAAgHIgDAAQgGAAgDACg");
	this.shape_7.setTransform(60.9,129.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#330000").s().p("AAMAWIAAgbIgLASIgBAAIgKgRIAAAaIgKAAIAAgrIAKAAIAKAUIAMgUIAJAAIAAArg");
	this.shape_8.setTransform(56,129.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#330000").s().p("AgKAUQgFgDgDgGQgCgFgBgGQABgFACgFQADgGAFgDQAFgDAFAAQAHAAAFADQAFADACAGQADAFAAAFQAAAGgDAFQgCAGgFADQgFADgHAAQgFAAgFgDgAgIgJQgDAEAAAFQAAAGADAEQAEAFAEAAQAGAAADgFQADgEAAgGQAAgFgDgEQgDgFgGAAQgEAAgEAFg");
	this.shape_9.setTransform(50.8,129.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#330000").s().p("AAPAbIAAgIIgdAAIAAAIIgKAAIAAgQIAGAAQAGgJAAgLIAAgRIAgAAIAAAlIAFAAIAAAQgAgCgJQAAAJgCADQgCAFgCADIASAAIAAgcIgMAAg");
	this.shape_10.setTransform(45.3,129.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#330000").s().p("AgDAVQAAgBgBgBQAAAAAAgBQAAAAAAgBQgBAAAAgBQAAgBABAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBABAAQABAAAAgBQABAAAAAAQAAAAAAAAQAAAAABAAQAAAAABAAQAAABABAAQAAAAABABQAAAAABABQAAAAAAABQAAAAAAABQABAAAAABQAAABgBAAQAAABAAAAQAAABAAAAQgBABAAABQgBAAAAAAQgBAAAAABQgBAAAAAAQgBAAAAAAQAAAAAAAAQAAAAgBAAQAAgBgBAAQgBAAAAAAgAgDgLQAAAAgBAAQAAgBAAAAQAAgBAAgBQgBAAAAgBQAAgBABAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQABAAAAAAQABgBAAAAQAAAAAAAAQAAAAABAAQAAAAABABQAAAAABAAQAAABABAAQAAAAABABQAAAAAAABQAAAAAAABQABAAAAABQAAABgBAAQAAABAAABQAAAAAAABQgBAAAAAAQgBABAAAAQgBABAAAAQgBAAAAAAQgBAAAAAAQAAAAAAAAQAAAAgBAAQAAAAgBgBQgBAAAAgBg");
	this.shape_11.setTransform(38.4,129.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#330000").s().p("AgJAUQgFgDgDgGQgDgFAAgGQAAgFADgFQADgGAFgDQAEgDAFAAQAHAAAGAEQAEAEACAFQACAGAAADIAAADIgfAAQAAAFADADQAEADADAAQAEAAADgBQADgCABgCIAIAEQgDAFgFACQgGADgFAAQgFAAgEgDgAgHgLQgDADAAAGIAWAAQAAgGgEgDQgDgDgFAAQgDAAgEADg");
	this.shape_12.setTransform(34.8,129.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#330000").s().p("AgDAWIAAgjIgPAAIAAgIIAlAAIAAAIIgPAAIAAAjg");
	this.shape_13.setTransform(30.2,129.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#330000").s().p("AAIAfIAAgeIgPAeIgKAAIAAgsIAKAAIAAAcIAPgcIAKAAIAAAsgAgHgVQgDgCgBgFIAGgCIADAEIACABIADgBQABgBAAAAQABAAAAgBQAAAAAAgBQAAAAABgBIAFACQgBAFgDACQgEACgDAAQgDAAgEgCg");
	this.shape_14.setTransform(25.7,128.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#330000").s().p("AgKAVQgEgBgCgEQgBgDgBgDQAAgIAGgCQAFgDAFgBIALAAQAAgKgJAAIgEABIgEAFIgHgEQACgEAFgDQAFgDAEAAQAFAAAEACQAEACADAEQABAFAAAGIAAAZIgHAAIgBgEQgHAFgFAAQgEAAgEgCgAgDACQgFACAAAFQABADACACQACACADAAQADAAADgDQADgCAAgEIAAgHIgDAAQgGAAgDACg");
	this.shape_15.setTransform(20.8,129.1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#330000").s().p("AgIAUQgFgDgCgFQgDgFAAgHQAAgFADgGQACgFAFgDQAFgDAFAAQAFAAAFACQAFADACAEIgIAEQgBgCgDgBQgCgCgDAAQgEAAgDAEQgDAFAAAFQAAAGADAFQADAEAEAAQADAAACgCQADgBABgCIAIAEQgDAEgEADQgFACgFAAQgFAAgFgDg");
	this.shape_16.setTransform(16.4,129.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#330000").s().p("AgKAVQgDgBgDgEQgCgDAAgDQAAgIAGgCQAEgDAGgBIALAAQAAgKgJAAIgEABIgEAFIgGgEQABgEAFgDQAFgDAEAAQAFAAAEACQAEACACAEQACAFAAAGIAAAZIgGAAIgCgEQgHAFgFAAQgEAAgEgCgAgDACQgFACAAAFQAAADADACQADACACAAQADAAADgDQADgCAAgEIAAgHIgDAAQgGAAgDACg");
	this.shape_17.setTransform(8.9,129.1);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#330000").s().p("AAIAWIAAgSIgPAAIAAASIgKAAIAAgrIAKAAIAAASIAPAAIAAgSIAJAAIAAArg");
	this.shape_18.setTransform(4.4,129.1);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#330000").s().p("AAIAWIAAgOIgIAAIgGAOIgLAAIAJgPQgEgCgCgEQgCgCAAgEQAAgFABgDQACgEAEgCQAEgCAFAAIARAAIAAArgAgBgNIgEACQgBACgBADQABAEABABIAEABIABAAIAIAAIAAgNIgIAAg");
	this.shape_19.setTransform(284.1,120.3);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#330000").s().p("AAJAWIAAgcIgQAcIgKAAIAAgrIAKAAIAAAbIAQgbIAJAAIAAArg");
	this.shape_20.setTransform(279.6,120.3);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#330000").s().p("AAJAdIAAgNIgbAAIAAgsIAJAAIAAAjIAOAAIAAgjIAJAAIAAAjIAFAAIAAAWg");
	this.shape_21.setTransform(274.7,121);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#330000").s().p("AgKAVQgEgBgCgEQgCgDAAgDQAAgIAGgCQAFgDAFgBIALAAQAAgKgJAAIgEABIgEAFIgHgEQADgEAEgDQAFgDAEAAQAFAAAEACQAEACACAEQACAFAAAGIAAAZIgGAAIgCgEQgHAFgFAAQgFAAgDgCgAgDACQgFACAAAFQABADACACQACACADAAQADAAADgDQADgCAAgEIAAgHIgDAAQgGAAgDACg");
	this.shape_22.setTransform(269.8,120.3);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#330000").s().p("AgTAgIAAg+IAJAAIAAAFQADgDADgBQAEgCACAAQAFAAAEADQAFADACAFQACAFAAAHQAAAHgCADQgCAGgEADQgFADgFAAQgCAAgEgCIgGgEIAAAYgAgIgSQgDAEAAAGQAAAHADACQAEAFAEAAQAFAAADgFQADgCAAgGQAAgHgDgEQgEgFgEAAQgEAAgEAFg");
	this.shape_23.setTransform(265.2,121.2);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#330000").s().p("AgKAVQgDgBgCgEQgCgDgBgDQABgIAFgCQAEgDAGgBIALAAQAAgKgJAAIgEABIgDAFIgHgEQACgEAEgDQAFgDAEAAQAFAAAEACQAEACACAEQADAFAAAGIAAAZIgHAAIgCgEQgHAFgGAAQgDAAgEgCgAgEACQgDACAAAFQAAADACACQADACACAAQADAAADgDQADgCAAgEIAAgHIgDAAQgGAAgEACg");
	this.shape_24.setTransform(260.2,120.3);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#330000").s().p("AgRAWIgCAAIAAgKIABABIADAAQACAAACgFIAAgNIAAgQIAfAAIAAArIgKAAIAAgjIgMAAIAAAIQAAANgCAHQgEAIgFAAIgEgBg");
	this.shape_25.setTransform(255.5,120.4);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#330000").s().p("AAHAWIgPgTIAAATIgJAAIAAgrIAJAAIAAAPIANgPIALAAIgRAVIATAWg");
	this.shape_26.setTransform(251.1,120.3);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#330000").s().p("AgKAUQgFgDgCgGQgDgFAAgGQAAgFADgFQACgGAFgDQAGgDAEAAQAIAAAFAEQAEAEACAFQACAGAAADIAAADIgfAAQAAAFAEADQADADAEAAQADAAADgBQADgCACgCIAHAEQgDAFgFACQgFADgGAAQgEAAgGgDgAgGgLQgEADAAAGIAWAAQgBgGgDgDQgDgDgFAAQgDAAgDADg");
	this.shape_27.setTransform(246.2,120.3);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#330000").s().p("AAPAbIAAgIIgdAAIAAAIIgKAAIAAgQIAGAAQAGgJAAgLIAAgRIAgAAIAAAlIAFAAIAAAQgAgCgJQAAAJgCADQgCAFgCADIASAAIAAgcIgMAAg");
	this.shape_28.setTransform(240.8,120.8);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#330000").s().p("AAIAWIAAgOIgIAAIgGAOIgLAAIAJgPQgEgCgCgEQgCgCAAgEQAAgFABgDQACgEAEgCQAEgCAFAAIARAAIAAArgAgBgNIgEACQgBACgBADQABAEABABIAEABIABAAIAIAAIAAgNIgIAAg");
	this.shape_29.setTransform(232.7,120.3);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#330000").s().p("AgKAVQgEgBgCgEQgBgDAAgDQAAgIAEgCQAGgDAFgBIALAAQAAgKgJAAIgEABIgEAFIgHgEQACgEAFgDQAFgDAEAAQAFAAAEACQAEACADAEQABAFAAAGIAAAZIgHAAIgBgEQgHAFgFAAQgFAAgDgCgAgEACQgEACAAAFQABADACACQACACADAAQADAAADgDQADgCAAgEIAAgHIgDAAQgGAAgEACg");
	this.shape_30.setTransform(228.2,120.3);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#330000").s().p("AAIAWIAAgSIgPAAIAAASIgKAAIAAgrIAKAAIAAASIAPAAIAAgSIAJAAIAAArg");
	this.shape_31.setTransform(223.7,120.3);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#330000").s().p("AgDAWIAAgjIgOAAIAAgIIAjAAIAAAIIgNAAIAAAjg");
	this.shape_32.setTransform(219.2,120.3);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#330000").s().p("AAHAWIgPgTIAAATIgJAAIAAgrIAJAAIAAAPIAOgPIAKAAIgRAVIATAWg");
	this.shape_33.setTransform(214.9,120.3);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#330000").s().p("AgKAUQgEgDgDgGQgDgFAAgGQAAgFADgFQADgGAEgDQAFgDAFAAQAHAAAGAEQAEAEACAFQACAGAAADIAAADIgfAAQABAFACADQAEADADAAQAEAAADgBQADgCACgCIAHAEQgDAFgFACQgGADgFAAQgFAAgFgDgAgHgLQgCADgBAGIAWAAQgBgGgDgDQgDgDgFAAQgDAAgEADg");
	this.shape_34.setTransform(210,120.3);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#330000").s().p("AgKAUQgFgDgDgGQgCgFgBgGQABgFACgFQADgGAFgDQAFgDAFAAQAHAAAFADQAFADACAGQADAFAAAFQAAAGgDAFQgCAGgFADQgFADgHAAQgFAAgFgDgAgIgJQgDAEAAAFQAAAGADAEQAEAFAEAAQAGAAADgFQADgEAAgGQAAgFgDgEQgDgFgGAAQgEAAgEAFg");
	this.shape_35.setTransform(205.1,120.3);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#330000").s().p("AgTAgIAAg+IAJAAIAAAFQADgDADgBQAEgCACAAQAFAAAEADQAFADACAFQACAFAAAHQAAAHgCADQgCAGgEADQgFADgFAAQgCAAgEgCIgGgEIAAAYgAgIgSQgDAEAAAGQAAAHADACQAEAFAEAAQAFAAADgFQADgCAAgGQAAgHgDgEQgEgFgEAAQgEAAgEAFg");
	this.shape_36.setTransform(200.2,121.2);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#330000").s().p("AAMAfIAAg0IgYAAIAAA0IgKAAIAAg9IAtAAIAAA9g");
	this.shape_37.setTransform(194.8,119.5);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#330000").s().p("AgDAEQAAgBAAAAQgBgBAAAAQAAgBAAAAQgBgBAAAAQAAAAABAAQAAAAAAgBQAAAAABgBQAAgBAAAAQABAAAAgBQABAAAAAAQABAAAAAAQAAgBAAAAQAAAAABABQABAAAAAAQABAAAAAAQABABAAAAQAAAAABABQAAABAAAAQAAABAAAAQABAAAAAAQAAAAgBABQAAAAAAABQAAAAAAABQgBAAAAABQAAAAgBABQgBAAAAAAQgBAAAAAAQgBABAAAAQAAAAAAgBQAAAAgBAAQAAAAgBAAQAAgBgBAAg");
	this.shape_38.setTransform(188,122.1);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#330000").s().p("AgKAVQgDgBgCgEQgCgDgBgDQABgIAEgCQAFgDAGgBIALAAQAAgKgJAAIgEABIgDAFIgHgEQACgEAEgDQAFgDAEAAQAFAAAEACQAEACACAEQADAFAAAGIAAAZIgHAAIgCgEQgHAFgGAAQgDAAgEgCgAgDACQgEACAAAFQAAADACACQADACACAAQADAAADgDQADgCAAgEIAAgHIgDAAQgGAAgDACg");
	this.shape_39.setTransform(184.6,120.3);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#330000").s().p("AAPAbIAAgIIgdAAIAAAIIgKAAIAAgQIAGAAQAGgJAAgLIAAgRIAgAAIAAAlIAFAAIAAAQgAgCgJQAAAJgCADQgCAFgCADIASAAIAAgcIgMAAg");
	this.shape_40.setTransform(179.4,120.8);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#330000").s().p("AgKAUQgFgDgDgGQgCgFgBgGQABgFACgFQADgGAFgDQAFgDAFAAQAHAAAFADQAFADACAGQADAFAAAFQAAAGgDAFQgCAGgFADQgFADgHAAQgFAAgFgDgAgIgJQgDAEAAAFQAAAGADAEQAEAFAEAAQAGAAADgFQADgEAAgGQAAgFgDgEQgDgFgGAAQgEAAgEAFg");
	this.shape_41.setTransform(174,120.3);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#330000").s().p("AgOAWIAAgrIAdAAIAAAIIgUAAIAAAjg");
	this.shape_42.setTransform(169.7,120.3);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#330000").s().p("AgKAdQgEgDgEgFQgCgFAAgGIABgGIACgEIACgCIAPgcIALAAIgMAXIACgBQAFAAAEACQAFADADADQADAEAAAGQAAAGgDAFQgDAFgFADQgEACgGAAQgEAAgGgCgAgGACQgEADAAAFQAAAFAEAEQACADAEAAQAEAAADgDQAEgEAAgFQAAgFgEgDQgDgCgEAAQgEAAgCACg");
	this.shape_43.setTransform(162.1,119.5);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#330000").s().p("AAAAfIAAgwIgJAHIAAgKIAOgKIAFAAIAAA9g");
	this.shape_44.setTransform(157.7,119.5);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#330000").s().p("AgMAcQgGgEgDgHQgDgIAAgJQAAgJADgHQADgHAGgEQAGgEAGABQAHgBAGAEQAGAEADAHQADAHAAAJQAAAJgDAIQgDAHgGAEQgGADgHABQgGgBgGgDgAgHgTQgDADgCAGQgCAFAAAFQAAAGACAGQACAFADADQAEADADAAQAHAAAEgHQAEgGAAgKQAAgJgEgHQgEgGgHAAQgDAAgEADg");
	this.shape_45.setTransform(153.3,119.5);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#330000").s().p("AgSAfIAAgEIASgZIAGgIQACgEAAgDQAAgEgCgCQgDgDgDAAQgDAAgDADQgCACgBAEQABAGAEACIgGAFQgEAAgCgDQgCgEAAgFQAAgGACgEQADgEAEgCQAFgCAEAAQAEAAAEACQAFACACAEQADAEAAAGQAAAHgGAHIgOAUIAVAAIAAAJg");
	this.shape_46.setTransform(148.3,119.4);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#330000").s().p("AgKAVQgEgBgCgEQgBgDAAgDQAAgIAEgCQAGgDAFgBIALAAQAAgKgJAAIgEABIgEAFIgHgEQACgEAFgDQAFgDAEAAQAFAAAEACQAEACADAEQABAFAAAGIAAAZIgHAAIgBgEQgHAFgFAAQgFAAgDgCgAgEACQgEACAAAFQABADACACQACACADAAQADAAADgDQADgCAAgEIAAgHIgDAAQgGAAgEACg");
	this.shape_47.setTransform(140.4,120.3);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#330000").s().p("AgDAWIAAgjIgPAAIAAgIIAkAAIAAAIIgNAAIAAAjg");
	this.shape_48.setTransform(136.1,120.3);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#330000").s().p("AgIAUQgFgDgCgFQgDgFAAgHQAAgFADgGQACgFAFgDQAFgDAFAAQAFAAAFACQAFADACAEIgIAEQgBgCgDgBQgCgCgDAAQgEAAgDAEQgDAFAAAFQAAAGADAFQADAEAEAAQADAAACgCQADgBABgCIAIAEQgDAEgEADQgFACgFAAQgFAAgFgDg");
	this.shape_49.setTransform(131.7,120.3);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#330000").s().p("AgKAgIAIgUIgSgqIAKAAIAKAeIALgeIAKAAIgVA+g");
	this.shape_50.setTransform(127.1,121.3);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#330000").s().p("AgOAWIAAgrIAdAAIAAAIIgUAAIAAAjg");
	this.shape_51.setTransform(123,120.3);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#330000").s().p("AgSAWIAAgrIAUAAQAHAAAEADQAEAEAAAGQAAADgCACQgBADgDAAQAEAAACADQACADAAAEQAAADgCADIgGAFQgEABgEAAgAgJAOIALAAQAEAAACgCQAAAAABgBQAAAAAAAAQAAgBABgBQAAAAAAgBQAAAAAAgBQgBgBAAAAQAAgBAAAAQgBgBAAAAQgCgCgEAAIgLAAgAgJgCIAKAAQADAAACgCQAAAAABgBQAAAAAAAAQAAgBABgBQAAAAAAgBQAAAAAAgBQgBgBAAAAQAAgBAAAAQgBAAAAgBQgCgBgDAAIgKAAg");
	this.shape_52.setTransform(118.6,120.3);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#330000").s().p("AgKAVQgDgBgDgEQgCgDAAgDQAAgIAGgCQAEgDAGgBIALAAQAAgKgJAAIgEABIgEAFIgGgEQABgEAFgDQAFgDAEAAQAFAAAEACQAEACACAEQACAFAAAGIAAAZIgGAAIgCgEQgHAFgFAAQgEAAgEgCgAgDACQgFACAAAFQAAADADACQADACACAAQADAAADgDQADgCAAgEIAAgHIgDAAQgGAAgDACg");
	this.shape_53.setTransform(113.7,120.3);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#330000").s().p("AAAAfIAAgwIgJAHIAAgKIAOgKIAFAAIAAA9g");
	this.shape_54.setTransform(107,119.5);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#330000").s().p("AgIAeIgIgDIgEgCIAFgIIACACIAGACIAHACQACAAADgCQAEgCABgDQABgCAAgDQAAgFgDgDQgDgDgFAAIgHAAIAAgDIAMgSIgUAAIAAgJIAiAAIAAAEIgQATQAFABADACQAEACADACQACAFAAAGQAAAHgDAFQgEAEgFACQgGACgCAAIgIgBg");
	this.shape_55.setTransform(102.8,119.5);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#330000").s().p("AgKAUQgFgDgDgGQgCgFgBgGQABgFACgFQADgGAFgDQAFgDAFAAQAHAAAFADQAFADACAGQADAFAAAFQAAAGgDAFQgCAGgFADQgFADgHAAQgFAAgFgDgAgIgJQgDAEAAAFQAAAGADAEQAEAFAEAAQAGAAADgFQADgEAAgGQAAgFgDgEQgDgFgGAAQgEAAgEAFg");
	this.shape_56.setTransform(94.7,120.3);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#330000").s().p("AAIAWIAAgjIgPAAIAAAjIgKAAIAAgrIAiAAIAAArg");
	this.shape_57.setTransform(89.9,120.3);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#330000").s().p("AAAAfIAAgwIgJAHIAAgKIAOgKIAFAAIAAA9g");
	this.shape_58.setTransform(83,119.5);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#330000").s().p("AgIAUQgFgDgCgFQgDgFAAgHQAAgFADgGQACgFAFgDQAFgDAFAAQAFAAAFACQAFADACAEIgIAEQgBgCgDgBQgCgCgDAAQgEAAgDAEQgDAFAAAFQAAAGADAFQADAEAEAAQADAAACgCQADgBABgCIAIAEQgDAEgEADQgFACgFAAQgFAAgFgDg");
	this.shape_59.setTransform(76.2,120.3);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#330000").s().p("AAIAWIAAgOIgIAAIgGAOIgKAAIAIgPQgEgCgCgEQgCgCAAgEQAAgFABgDQACgEAEgCQADgCAGAAIASAAIAAArgAgBgNIgEACQgBACgBADQABAEABABIAEABIABAAIAIAAIAAgNIgIAAg");
	this.shape_60.setTransform(68.8,120.3);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#330000").s().p("AAIAWIAAgcIgQAcIgJAAIAAgrIAJAAIAAAbIAQgbIAKAAIAAArg");
	this.shape_61.setTransform(64.3,120.3);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#330000").s().p("AAJAdIAAgNIgbAAIAAgsIAKAAIAAAjIANAAIAAgjIAJAAIAAAjIAFAAIAAAWg");
	this.shape_62.setTransform(59.4,121);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#330000").s().p("AAHAWIgPgTIAAATIgJAAIAAgrIAJAAIAAAPIANgPIALAAIgRAVIATAWg");
	this.shape_63.setTransform(54.8,120.3);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#330000").s().p("AASAfIgFgQIgHADIgGABIgFgBIgGgDIgGAQIgKAAIAXg9IAJAAIAXA9gAgIAHQAFADADAAQAEAAAFgDIgJgZg");
	this.shape_64.setTransform(49.2,119.5);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#330000").s().p("AgDAEQAAgBAAAAQgBgBAAAAQAAgBAAAAQgBgBAAAAQAAAAABAAQAAAAAAgBQAAAAABgBQAAgBAAAAQABAAAAgBQABAAAAAAQABAAAAAAQAAgBAAAAQAAAAABABQABAAAAAAQABAAAAAAQABABAAAAQAAAAABABQAAABAAAAQAAABAAAAQAAAAAAAAQAAAAAAABQAAAAAAABQAAAAAAABQgBAAAAABQAAAAgBABQgBAAAAAAQgBAAAAAAQgBABAAAAQAAAAAAgBQAAAAgBAAQAAAAgBAAQAAgBgBAAg");
	this.shape_65.setTransform(42.1,122.1);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#330000").s().p("AgKAdQgFgDgDgFQgCgFAAgGIABgGIACgEIABgCIAQgcIALAAIgMAXIABgBQAGAAAEACQAFADADADQADAEAAAGQAAAGgDAFQgDAFgFADQgEACgGAAQgFAAgFgCgAgHACQgDADAAAFQAAAFADAEQAEADADAAQAEAAADgDQADgEABgFQgBgFgDgDQgCgCgFAAQgDAAgEACg");
	this.shape_66.setTransform(39,119.5);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#330000").s().p("AAAAfIAAgwIgJAHIAAgKIAOgKIAFAAIAAA9g");
	this.shape_67.setTransform(34.7,119.5);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#330000").s().p("AgMAcQgGgEgDgHQgDgIAAgJQAAgJADgHQADgHAGgEQAGgEAGABQAHgBAGAEQAGAEADAHQADAHAAAJQAAAJgDAIQgDAHgGAEQgGADgHABQgGgBgGgDgAgHgTQgDADgCAGQgCAFAAAFQAAAGACAGQACAFADADQAEADADAAQAHAAAEgHQAEgGAAgKQAAgJgEgHQgEgGgHAAQgDAAgEADg");
	this.shape_68.setTransform(30.3,119.5);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#330000").s().p("AgSAfIAAgEIASgZIAHgIQABgEABgDQgBgEgCgCQgDgDgDAAQgDAAgDADQgCACAAAEQAAAGAEACIgFAFQgFAAgCgDQgCgEAAgFQAAgGACgEQADgEAFgCQAEgCAEAAQAFAAAEACQAEACADAEQACAEAAAGQAAAHgHAHIgNAUIAVAAIAAAJg");
	this.shape_69.setTransform(25.2,119.4);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#330000").s().p("AgCAEQgBgBAAAAQgBgBAAAAQAAgBAAAAQgBgBAAAAQAAAAABAAQAAAAAAgBQAAAAABgBQAAgBABAAQAAAAAAgBQABAAAAAAQABAAAAAAQAAgBAAAAQAAAAABABQABAAAAAAQABAAAAAAQABABAAAAQAAAAABABQAAABAAAAQAAABAAAAQABAAAAAAQAAAAgBABQAAAAAAABQAAAAAAABQgBAAAAABQgBAAAAABQgBAAAAAAQgBAAAAAAQgBABAAAAQAAAAAAgBQAAAAgBAAQAAAAgBAAQAAgBAAAAg");
	this.shape_70.setTransform(21.7,122.1);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#330000").s().p("AAAAfIAAgwIgJAHIAAgKIAOgKIAFAAIAAA9g");
	this.shape_71.setTransform(19.1,119.5);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#330000").s().p("AgMAcQgGgEgDgHQgDgIAAgJQAAgJADgHQADgHAGgEQAGgEAGABQAHgBAGAEQAGAEADAHQADAHAAAJQAAAJgDAIQgDAHgGAEQgGADgHABQgGgBgGgDgAgHgTQgDADgCAGQgCAFAAAFQAAAGACAGQACAFADADQAEADADAAQAHAAAEgHQAEgGAAgKQAAgJgEgHQgEgGgHAAQgDAAgEADg");
	this.shape_72.setTransform(14.7,119.5);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#330000").s().p("AgCAEQgBgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAAAAAAAQAAAAAAgBQAAAAABgBQAAgBABAAQAAAAAAgBQABAAAAAAQABAAAAAAQAAgBAAAAQAAAAABABQABAAAAAAQABAAAAAAQABABAAAAQAAAAABABQAAABAAAAQAAABAAAAQAAAAAAAAQAAAAAAABQAAAAAAABQAAAAAAABQgBAAAAABQgBAAAAABQgBAAAAAAQgBAAAAAAQgBABAAAAQAAAAAAgBQAAAAgBAAQAAAAgBAAQAAgBAAAAg");
	this.shape_73.setTransform(11.1,122.1);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#330000").s().p("AgIAeIgIgDIgEgCIAFgIIACACIAGACIAHACQACAAADgCQAEgCABgDQABgCAAgDQAAgFgDgDQgDgDgFAAIgHAAIAAgDIAMgSIgUAAIAAgJIAiAAIAAAEIgQATQAFABADACQAEACADACQADAFgBAGQAAAHgDAFQgEAEgFACQgGACgCAAIgIgBg");
	this.shape_74.setTransform(7.9,119.5);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("#330000").s().p("AAAAfIAAgwIgJAHIAAgKIAOgKIAFAAIAAA9g");
	this.shape_75.setTransform(3.6,119.5);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#330000").s().p("AgDAWIAAgjIgOAAIAAgIIAjAAIAAAIIgOAAIAAAjg");
	this.shape_76.setTransform(269,110.7);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("#330000").s().p("AgKAUQgFgDgDgGQgCgFgBgGQABgFACgFQADgGAFgDQAFgDAFAAQAHAAAFADQAFADACAGQADAFAAAFQAAAGgDAFQgCAGgFADQgFADgHAAQgFAAgFgDgAgIgJQgDAEAAAFQAAAGADAEQAEAFAEAAQAGAAADgFQADgEAAgGQAAgFgDgEQgDgFgGAAQgEAAgEAFg");
	this.shape_77.setTransform(264.3,110.7);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#330000").s().p("AgJAdQgGgDgCgFQgDgFAAgGIABgGIACgEIACgCIAPgcIALAAIgMAXIACgBQAEAAAFACQAFADADADQADAEAAAGQAAAGgDAFQgDAFgFADQgFACgFAAQgFAAgEgCgAgGACQgEADAAAFQAAAFAEAEQACADAEAAQAEAAAEgDQACgEAAgFQAAgFgCgDQgEgCgEAAQgEAAgCACg");
	this.shape_78.setTransform(256.3,109.8);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f("#330000").s().p("AAAAfIAAgwIgJAIIAAgLIAOgKIAFAAIAAA9g");
	this.shape_79.setTransform(252,109.8);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f("#330000").s().p("AAAAfIAAgwIgJAIIAAgLIAOgKIAFAAIAAA9g");
	this.shape_80.setTransform(248.7,109.8);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f("#330000").s().p("AgMAcQgGgEgDgHQgDgHAAgKQAAgIADgIQADgHAGgEQAGgEAGAAQAHAAAGAEQAGAEADAHQADAIAAAIQAAAKgDAHQgDAHgGAEQgGAEgHAAQgGAAgGgEgAgHgTQgDADgCAGQgCAFAAAFQAAAHACAEQACAGADADQAEADADAAQAHAAAEgGQAEgHAAgKQAAgJgEgHQgEgGgHAAQgDAAgEADg");
	this.shape_81.setTransform(244.3,109.8);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f("#330000").s().p("AgMAcQgGgEgDgHQgDgHAAgKQAAgIADgIQADgHAGgEQAGgEAGAAQAHAAAGAEQAGAEADAHQADAIAAAIQAAAKgDAHQgDAHgGAEQgGAEgHAAQgGAAgGgEgAgHgTQgDADgCAGQgCAFAAAFQAAAHACAEQACAGADADQAEADADAAQAHAAAEgGQAEgHAAgKQAAgJgEgHQgEgGgHAAQgDAAgEADg");
	this.shape_82.setTransform(238.1,109.8);

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.f("#330000").s().p("AgMAcQgGgEgDgHQgDgHAAgKQAAgIADgIQADgHAGgEQAGgEAGAAQAHAAAGAEQAGAEADAHQADAIAAAIQAAAKgDAHQgDAHgGAEQgGAEgHAAQgGAAgGgEgAgHgTQgDADgCAGQgCAFAAAFQAAAHACAEQACAGADADQAEADADAAQAHAAAEgGQAEgHAAgKQAAgJgEgHQgEgGgHAAQgDAAgEADg");
	this.shape_83.setTransform(231.9,109.8);

	this.shape_84 = new cjs.Shape();
	this.shape_84.graphics.f("#330000").s().p("AgIAeIgIgDIgEgCIAFgIIACACIAGACIAHACQACAAADgCQAEgCABgDQABgCAAgDQAAgFgDgDQgDgDgFAAIgHAAIAAgDIAMgSIgUAAIAAgJIAiAAIAAAEIgQATQAFABADACQAEACADACQADAFgBAGQAAAHgDAFQgEAEgFACQgGACgCAAIgIgBg");
	this.shape_84.setTransform(226.6,109.8);

	this.shape_85 = new cjs.Shape();
	this.shape_85.graphics.f("#330000").s().p("AAAAfIAAgwIgJAIIAAgLIAOgKIAFAAIAAA9g");
	this.shape_85.setTransform(222.3,109.8);

	this.shape_86 = new cjs.Shape();
	this.shape_86.graphics.f("#330000").s().p("AgSAfIAAgEIASgZIAGgIQACgEAAgDQAAgEgDgCQgCgDgDAAQgDAAgCADQgDACgBAEQAAAGAFACIgGAFQgDAAgCgDQgDgEAAgFQAAgGADgEQACgEAEgCQAFgCAEAAQAEAAAEACQAFACACAEQADAEAAAGQAAAHgGAHIgOAUIAVAAIAAAJg");
	this.shape_86.setTransform(218.7,109.8);

	this.shape_87 = new cjs.Shape();
	this.shape_87.graphics.f("#330000").s().p("AgUAfIAbg0IgbAAIAAgJIApAAIAAAEIgeA5g");
	this.shape_87.setTransform(213.9,109.8);

	this.shape_88 = new cjs.Shape();
	this.shape_88.graphics.f("#330000").s().p("AgUAfIAbg0IgbAAIAAgJIApAAIAAAEIgeA5g");
	this.shape_88.setTransform(208.9,109.8);

	this.shape_89 = new cjs.Shape();
	this.shape_89.graphics.f("#330000").s().p("AAAAZQgBgBgBgFIgJgVIAAATIAFABQAAAAABABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQgBAAAAAAIgGABIgFAAIgGgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQgBgBAAAAQABgEAEgBIAAghQgEgBgBgEIABgDQABAAAAAAQABgBAAAAQABAAABAAQAAAAABAAIAEAAIAEABIACAFIAJAWIAAgTQgGAAAAgFQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBAAAAQACgBADAAIAFAAIAGABQAAAAABABQAAAAAAAAQAAABAAAAQABABAAAAQAAAEgFABIAAAhIAAAFIgCADIgEABQAAAAgBAAQAAAAgBAAQAAAAAAgBQAAAAAAAAgAARAQQgGAAAAgEIABgCQABgCAEAAIACAAQAEAAACACIAAACQAAAEgGAAgAALAAIAAgKQABgDACgCQABgCADAAQADAAADACQABACAAADIAAAKQABAFgIAAQgGAAgBgFgAARgJIAAAJQAAAAABAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAIAAgJQAAgBAAAAQAAgBAAAAQAAAAAAAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQAAAAAAABQgBAAAAABg");
	this.shape_89.setTransform(203.5,110.3);

	this.shape_90 = new cjs.Shape();
	this.shape_90.graphics.f("#330000").s().p("AgJAUQgFgDgDgGQgDgFAAgGQAAgFADgFQADgGAFgDQAEgDAFAAQAHAAAGAEQAEAEACAFQACAGAAADIAAADIgfAAQAAAFADADQAEADADAAQAEAAADgBQADgCABgCIAIAEQgDAFgFACQgGADgFAAQgFAAgEgDgAgHgLQgDADAAAGIAWAAQAAgGgEgDQgDgDgFAAQgDAAgEADg");
	this.shape_90.setTransform(195.4,110.7);

	this.shape_91 = new cjs.Shape();
	this.shape_91.graphics.f("#330000").s().p("AAJAWIAAgcIgQAcIgKAAIAAgrIAKAAIAAAbIAQgbIAJAAIAAArg");
	this.shape_91.setTransform(190.6,110.7);

	this.shape_92 = new cjs.Shape();
	this.shape_92.graphics.f("#330000").s().p("AAIAWIAAgSIgPAAIAAASIgJAAIAAgrIAJAAIAAASIAPAAIAAgSIAJAAIAAArg");
	this.shape_92.setTransform(185.9,110.7);

	this.shape_93 = new cjs.Shape();
	this.shape_93.graphics.f("#330000").s().p("AgKAUQgFgDgCgGQgDgFAAgGQAAgFADgFQACgGAFgDQAGgDAEAAQAIAAAEAEQAFAEACAFQACAGAAADIAAADIgfAAQABAFADADQADADAEAAQADAAADgBQADgCABgCIAIAEQgDAFgFACQgFADgGAAQgEAAgGgDgAgGgLQgDADgBAGIAWAAQgBgGgDgDQgDgDgFAAQgDAAgDADg");
	this.shape_93.setTransform(181.1,110.7);

	this.shape_94 = new cjs.Shape();
	this.shape_94.graphics.f("#330000").s().p("AgZAWIAAgrIAKAAIAAAjIAMAAIAAgjIAHAAIAAAjIAMAAIAAgjIAKAAIAAArg");
	this.shape_94.setTransform(175.5,110.7);

	this.shape_95 = new cjs.Shape();
	this.shape_95.graphics.f("#330000").s().p("AgKAUQgFgDgCgGQgDgFAAgGQAAgFADgFQACgGAFgDQAGgDAEAAQAIAAAEAEQAFAEACAFQACAGAAADIAAADIgfAAQABAFADADQADADAEAAQADAAADgBQADgCABgCIAIAEQgDAFgFACQgFADgGAAQgEAAgGgDgAgGgLQgDADgBAGIAWAAQgBgGgDgDQgDgDgFAAQgDAAgDADg");
	this.shape_95.setTransform(169.8,110.7);

	this.shape_96 = new cjs.Shape();
	this.shape_96.graphics.f("#330000").s().p("AgTAgIAAg+IAJAAIAAAFQADgDADgBQAEgCACAAQAFAAAEADQAFADACAFQACAFAAAHQAAAHgCADQgCAGgEADQgFADgFAAQgCAAgEgCIgGgEIAAAYgAgIgSQgDAEAAAGQAAAHADACQAEAFAEAAQAFAAADgFQADgCAAgGQAAgHgDgEQgEgFgEAAQgEAAgEAFg");
	this.shape_96.setTransform(165,111.6);

	this.shape_97 = new cjs.Shape();
	this.shape_97.graphics.f("#330000").s().p("AgIAVIgHgDIADgHIAFADIAHABQADAAADgCQACgCAAgDQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAgBgBgBQgCgBgDAAIgJAAIAAgGIAJAAQADAAACgBQAAAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAgBQAAAAAAgBQgBAAAAgBQAAAAgBgBQgCgBgDgBIgGABIgGADIgDgHIAEgBIAGgDIAFAAQAFAAADACIAGAEIABAGQAAAGgDAEQACAAABACIABAGQAAAEgCAEIgGAFQgEACgEAAQgDAAgFgCg");
	this.shape_97.setTransform(160.4,110.7);

	this.shape_98 = new cjs.Shape();
	this.shape_98.graphics.f("#330000").s().p("AgKAVQgDgBgDgEQgCgDAAgDQAAgIAGgCQAEgDAGgBIALAAQAAgKgJAAIgEABIgEAFIgGgEQABgEAFgDQAFgDAEAAQAFAAAEACQAEACACAEQACAFAAAGIAAAZIgGAAIgCgEQgHAFgFAAQgEAAgEgCgAgDACQgFACAAAFQAAADADACQADACACAAQADAAADgDQADgCAAgEIAAgHIgDAAQgGAAgDACg");
	this.shape_98.setTransform(156,110.7);

	this.shape_99 = new cjs.Shape();
	this.shape_99.graphics.f("#330000").s().p("AgVAfIAAg9IAXAAQAGAAAEACQAFACACAEQADAFAAAEQAAAGgDAFQgCACgFABQgEADgGAAIgNAAIAAAbgAgLgDIANAAQAFAAACgDQADgCAAgEQAAgEgDgCQgCgDgFAAIgNAAg");
	this.shape_99.setTransform(151.3,109.8);

	this.shape_100 = new cjs.Shape();
	this.shape_100.graphics.f("#330000").s().p("AgEABIgBgBIgBgDQAAgDADgCQACgCABAAQADAAACACQACACAAADIgBADQAAAAAAAAQAAABgBAAQAAABgBAAQAAAAgBABIgJAIg");
	this.shape_100.setTransform(144.6,112.7);

	this.shape_101 = new cjs.Shape();
	this.shape_101.graphics.f("#330000").s().p("AAAALIAOgLIgOgKIAAgNIAYAUIAAAHIgYAUgAgXALIAQgLIgQgKIAAgNIAaAWIAAADIgaAWg");
	this.shape_101.setTransform(140.6,110.5);

	this.shape_102 = new cjs.Shape();
	this.shape_102.graphics.f("#330000").s().p("AgMAdQgFgFgCgFIgBgJQAAgLADgIQAEgJAIgGQAGgFAOgDIACALIgQAEQgCACgCACIgEAGQAFgFAEAAQAGAAAEAEQAFADACAFQACAEAAAGQAAAGgCAGQgDAFgFADQgFADgGAAQgIAAgEgEgAgFAAQgCACgBADIgBAFIABAFQABADACADQACACADAAQAEAAADgEQADgDAAgGQAAgFgDgEQgDgCgEAAQgDAAgCABg");
	this.shape_102.setTransform(134.8,109.6);

	this.shape_103 = new cjs.Shape();
	this.shape_103.graphics.f("#330000").s().p("AgOATQgFgDAAgGQAAgIAFgCQAFgDAFgBIALgBQgBgHgGAAIgEABIgDADIgJgEQACgEAFgDQAFgDAEAAQAFAAAFACQAEADADAEQADAFAAAGIAAAYIgKAAIgBgEQgIAFgFAAQgGAAgEgEgAgDACQgDABAAAFQAAABAAAAQAAABAAAAQABABAAAAQABABAAAAQACACACAAQACAAADgCQACgCAAgDIAAgGIgDAAQgEAAgDABg");
	this.shape_103.setTransform(129.8,110.7);

	this.shape_104 = new cjs.Shape();
	this.shape_104.graphics.f("#330000").s().p("AAHAWIAAgRIgNAAIAAARIgMAAIAAgrIAMAAIAAARIANAAIAAgRIAMAAIAAArg");
	this.shape_104.setTransform(125,110.7);

	this.shape_105 = new cjs.Shape();
	this.shape_105.graphics.f("#330000").s().p("AgIAUQgFgDgCgFQgEgFAAgHQAAgFAEgGQACgFAFgDQAFgDAFAAQAFAAAFACQAFADADADIgKAGIgEgDIgEgBQgCAAgDAEQgDAEAAAEQAAAFADAEQADADACAAIAEgBIAEgCIAKAGQgDADgFADQgFACgFAAQgFAAgFgDg");
	this.shape_105.setTransform(120.2,110.7);

	this.shape_106 = new cjs.Shape();
	this.shape_106.graphics.f("#330000").s().p("AAHAfIAAgZIgNAZIgMAAIAAgsIAMAAIAAAXIANgXIAMAAIAAAsgAgHgVQgDgCgBgEIAHgDIACAEIACABQABAAAAAAQAAAAABAAQAAgBABAAQAAAAABAAQAAgBAAAAQABAAAAgBQAAAAABgBQAAAAAAgBIAGADQgBAEgEACQgDACgEABQgDgBgEgCg");
	this.shape_106.setTransform(115.4,109.8);

	this.shape_107 = new cjs.Shape();
	this.shape_107.graphics.f("#330000").s().p("AgKAUQgFgDgDgFQgDgGAAgGQAAgGADgFQADgFAFgDQAFgDAFAAQAHAAAFADQAFADADAFQACAGAAAFQAAAHgCAFQgDAFgFADQgFADgHAAQgFAAgFgDgAgFgIQgDAEgBAEQABAFADAEQACADADAAQAEAAADgDQADgEAAgFQAAgEgDgEQgDgEgEAAQgDAAgCAEg");
	this.shape_107.setTransform(110.3,110.7);

	this.shape_108 = new cjs.Shape();
	this.shape_108.graphics.f("#330000").s().p("AgUAgIAAg+IAMAAIAAAEIAGgEIAFgBQAGAAAEADQAEAEACAFQACAFAAAGQAAAIgEAHQgFAHgJAAIgFgBIgGgEIAAAXgAgHgRQgCADAAAGQAAAGACACQADAEAEAAQADAAADgEQADgCAAgGQAAgGgDgDQgDgEgDAAQgEAAgDAEg");
	this.shape_108.setTransform(105.4,111.6);

	this.shape_109 = new cjs.Shape();
	this.shape_109.graphics.f("#330000").s().p("AgFAWIAAggIgOAAIAAgLIAnAAIAAALIgOAAIAAAgg");
	this.shape_109.setTransform(100.4,110.7);

	this.shape_110 = new cjs.Shape();
	this.shape_110.graphics.f("#330000").s().p("AgIAUQgFgDgDgFQgCgFAAgHQAAgFACgGQADgFAFgDQAGgDAEAAQAFAAAFACQAFADACADIgJAGIgDgDIgFgBQgDAAgCAEQgDAEAAAEQAAAFADAEQACADADAAIAFgBIADgCIAJAGQgCADgFADQgFACgFAAQgEAAgGgDg");
	this.shape_110.setTransform(95.8,110.7);

	this.shape_111 = new cjs.Shape();
	this.shape_111.graphics.f("#330000").s().p("AgIAUQgFgDgDgFQgDgFAAgHQAAgFADgGQADgFAFgDQAGgDAEAAQAFAAAFACQAFADADADIgLAGIgDgDIgEgBQgCAAgDAEQgDAEAAAEQAAAFADAEQADADACAAIAEgBIADgCIALAGQgDADgFADQgFACgFAAQgEAAgGgDg");
	this.shape_111.setTransform(91.2,110.7);

	this.shape_112 = new cjs.Shape();
	this.shape_112.graphics.f("#330000").s().p("AgKAUQgFgDgDgFQgDgGAAgGQAAgGADgFQADgFAFgDQAFgDAFAAQAHAAAEADQAGADACAFQADAGAAAFQAAAHgDAFQgCAFgGADQgEADgHAAQgFAAgFgDgAgGgIQgCAEAAAEQAAAFACAEQADADADAAQAEAAADgDQADgEgBgFQABgEgDgEQgDgEgEAAQgDAAgDAEg");
	this.shape_112.setTransform(86.4,110.7);

	this.shape_113 = new cjs.Shape();
	this.shape_113.graphics.f("#330000").s().p("AAOAfIAAgjIgKAXIgHAAIgKgXIAAAjIgOAAIAAg9IAOAAIANAgIAOggIAOAAIAAA9g");
	this.shape_113.setTransform(80.5,109.8);

	this.shape_114 = new cjs.Shape();
	this.shape_114.graphics.f("#330000").s().p("AgCACIAAgDIAagWIAAANIgQAKIAQALIAAANgAgXAEIAAgHIAYgUIAAANIgOAKIAOALIAAANg");
	this.shape_114.setTransform(74.1,110.5);

	this.shape_115 = new cjs.Shape();
	this.shape_115.graphics.f("#330000").s().p("AgNAcQgIgEgDgHQgFgIAAgJQAAgIAFgIQADgHAIgEQAGgEAHAAQAIAAAGAEQAHAEAFAHQADAIAAAIQAAAJgDAIQgFAHgHAEQgGAEgIAAQgHAAgGgEgAgHgQQgEACgCAFQgCAFAAAEQAAAFACAFQACAFAEACQAEADADAAQAEAAAEgDQADgCACgFQADgFAAgFQAAgEgDgFQgCgFgDgCQgEgDgEAAQgDAAgEADg");
	this.shape_115.setTransform(65,109.8);

	this.shape_116 = new cjs.Shape();
	this.shape_116.graphics.f("#330000").s().p("AAPAfIgEgOQgHADgEAAQgDAAgHgDIgEAOIgPAAIAXg9IANAAIAXA9gAgGAHQAEABACAAQADAAAEgBIgHgXg");
	this.shape_116.setTransform(58.4,109.8);

	this.shape_117 = new cjs.Shape();
	this.shape_117.graphics.f("#330000").s().p("AgDABIAAgBIAAAAQgBAAAAAAQAAgBAAAAQgBgBAAAAQAAAAAAgBQAAgBAAAAQABgBAAAAQAAgBAAAAQABgBAAAAQABgBAAAAQABAAAAgBQABAAAAAAQAAAAAAAAQAAAAABAAQAAAAABAAQAAABABAAQAAAAABABQAAAAABABQAAAAAAABQABAAAAABQAAABAAAAIgBADIgCABIgIAJg");
	this.shape_117.setTransform(51.4,112.9);

	this.shape_118 = new cjs.Shape();
	this.shape_118.graphics.f("#330000").s().p("AAOAfIAAgbIgaAAIAAAbIgKAAIAAg9IAKAAIAAAbIAaAAIAAgbIAKAAIAAA9g");
	this.shape_118.setTransform(47.6,109.8);

	this.shape_119 = new cjs.Shape();
	this.shape_119.graphics.f("#330000").s().p("AgKAcQgGgEgEgHQgEgHAAgKQAAgIAEgHQAEgIAGgEQAHgEAGAAQAHAAAFADQAGACAEAFIgJAFQgDgDgDgBQgDgCgEAAQgDAAgEADQgFADgCAFQgDAGABAFQgBAHADAFQACAFAFADQAEADADAAQAEAAADgCQADgBADgDIAJAFQgEAFgGACQgGADgGAAQgGAAgHgEg");
	this.shape_119.setTransform(41.8,109.8);

	this.shape_120 = new cjs.Shape();
	this.shape_120.graphics.f("#330000").s().p("AAMAfIAAg0IgYAAIAAA0IgKAAIAAg9IAtAAIAAA9g");
	this.shape_120.setTransform(36.2,109.8);

	this.shape_121 = new cjs.Shape();
	this.shape_121.graphics.f("#330000").s().p("AgKAVQgDgBgCgEQgCgDgBgDQABgIAEgCQAFgDAGgBIALAAQAAgKgJAAIgEABIgDAFIgHgEQACgEAEgDQAFgDAEAAQAFAAAEACQAEACACAEQADAFAAAGIAAAZIgHAAIgCgEQgHAFgGAAQgDAAgEgCgAgEACQgDACAAAFQAAADACACQADACACAAQADAAADgDQADgCAAgEIAAgHIgDAAQgGAAgEACg");
	this.shape_121.setTransform(28,110.7);

	this.shape_122 = new cjs.Shape();
	this.shape_122.graphics.f("#330000").s().p("AAIAWIAAgjIgPAAIAAAjIgJAAIAAgrIAiAAIAAArg");
	this.shape_122.setTransform(23.5,110.7);

	this.shape_123 = new cjs.Shape();
	this.shape_123.graphics.f("#330000").s().p("AAIAWIAAgjIgPAAIAAAjIgKAAIAAgrIAiAAIAAArg");
	this.shape_123.setTransform(18.8,110.7);

	this.shape_124 = new cjs.Shape();
	this.shape_124.graphics.f("#330000").s().p("AgKAgIAIgVIgSgqIAKAAIAKAfIALgfIAKAAIgVA/g");
	this.shape_124.setTransform(14,111.6);

	this.shape_125 = new cjs.Shape();
	this.shape_125.graphics.f("#330000").s().p("AgTAgIAAg+IAJAAIAAAFQADgDADgBQAEgCACAAQAFAAAEADQAFADACAFQACAFAAAHQAAAHgCADQgCAGgEADQgFADgFAAQgCAAgEgCIgGgEIAAAYgAgIgSQgDAEAAAGQAAAHADACQAEAFAEAAQAFAAADgFQADgCAAgGQAAgHgDgEQgEgFgEAAQgEAAgEAFg");
	this.shape_125.setTransform(9.3,111.6);

	this.shape_126 = new cjs.Shape();
	this.shape_126.graphics.f("#330000").s().p("AgSAfIAAg9IAlAAIAAAJIgbAAIAAA0g");
	this.shape_126.setTransform(4.5,109.8);

	this.shape_127 = new cjs.Shape();
	this.shape_127.graphics.f("#330000").s().p("An5CGIAAgSQgKgBgHgGQgGgGAAgKQAAgKAGgFQAHgHAKgBIAAgRIAJAAIAAARQALABAHAGQAFAGABAKQgBAKgFAGQgHAGgLABIAAASgAnwBrQAGAAAEgEQAEgEAAgGQAAgFgEgEQgDgEgHgBgAoCBUQgEADAAAGQAAAGAEAEQADAEAGAAIAAgcQgGAAgDAFgAo/CGIAAhAIAJAAIAAAGQADgDAEgCQADgBAFAAQAEAAAFADQAEADADAEQACAGAAAHQAAAHgCAFQgDAGgEADQgEACgGAAQgEABgDgCIgHgEIAAAXgAo0BSQgDAFAAAGQAAAHADAEQAEAFAFgBQAGABADgFQADgEAAgGQAAgHgDgFQgDgEgGAAQgFAAgEAEgAvMB9IAAgIIgfAAIAAAIIgJAAIAAgQIAFAAQAGgJAAgNIAAgRIAiAAIAAAnIAFAAIAAAQgAvfBXQAAAJgCAFQgCAFgCADIAVAAIAAgeIgPAAgApTBzQAAAAAAgBQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQABAAAAgBQABAAAAAAQABAAAAAAQABAAAAAAQABAAABAAQABAAAAAAQABAAAAAAQABABAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAABAAABQAAAAAAABQAAAAAAABQAAAAAAABQgBABAAAAQgBAAAAABQgBAAAAAAQgBAAAAAAQgBAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAgBgBAAgAtMBzQgDgCgCgDQgCgDAAgDQAAgIAFgDQAFgEAFgBIAOgBQgBgKgIABIgHABQgCACgBADIgHgFQACgDAFgEQAEgCAHAAQAEAAAFACQAEACACAEQACAFAAAFIAAAcIgHAAIgBgEQgIAFgHgBQgEABgEgCgAtFBgQgEACAAAFQAAACADACQACACAEAAQADAAADgCQAEgCAAgEIAAgHIgEAAQgGAAgFACgAuxByQgEgDgDgGQgCgFgBgHQABgGACgGQADgFAEgDQAFgDAHAAQAHAAAGADQAEADADAFQACAGABAGQgBAHgCAFQgDAGgEADQgGACgHAAQgHAAgFgCgAuuBSQgDAFAAAGQAAAHADAEQADAFAGgBQAHABADgFQADgEAAgHQAAgGgDgFQgDgEgHAAQgGAAgDAEgAwmBzQAAAAAAgBQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgBAAgBQAAAAAAgBQABAAAAgBQAAAAAAgBQABAAABgBQAAAAABAAQAAAAABAAQAAAAABAAQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAQABABAAAAQAAABABAAQAAABAAAAQAAABAAABQAAAAAAABQAAAAAAABQgBAAAAABQAAABgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBgBgBAAgAxQByQgFgDgCgGQgEgFAAgHQAAgGAEgGQACgFAFgDQAFgDAHAAQAHAAAFADQAFAFACAFQABAFAAAGIAAADIghAAQABAFADADQADADAGAAQADAAADgCQAEgBABgCIAIAEQgDAEgFADQgGADgFgBQgHAAgFgCgAxNBRQgDADgBAFIAYAAQAAgFgDgDQgEgDgEAAQgGAAgDADgAzcBzQgEgCgCgDQgBgDgBgDQAAgIAGgDQAFgEAFgBIANgBQAAgKgJABIgGABQgCACgCADIgHgFQACgDAFgEQAFgCAGAAQAFAAAEACQAEACACAEQACAFAAAFIAAAcIgHAAIgBgEQgHAFgHgBQgEABgEgCgAzVBgQgFACAAAFQABACACACQACACAEAAQAEAAADgCQADgCAAgEIAAgHIgDAAQgHAAgEACgA0GByQgEgDgDgFQgDgFAAgHQAAgIADgFQADgFAEgDQAGgDAGAAQAFAAAFACQAFADACADIgHAFQgCgCgDgCQgCgBgDAAQgFAAgEAEQgDAFAAAGQAAAHADAFQAEADAFAAQADAAACgBQADgBACgCIAHAEQgDAEgEADQgFABgFAAQgGABgGgDgA1TBzQgEgCgCgDQgCgDAAgDQAAgIAFgDQAFgEAFgBIAOgBQAAgKgJABIgHABQgCACgBADIgHgFQACgDAFgEQAFgCAFAAQAFAAAEACQAEACADAEQACAFAAAFIAAAcIgHAAIgCgEQgHAFgHgBQgEABgDgCgA1NBgQgEACAAAFQAAACACACQADACAEAAQADAAAEgCQADgCAAgEIAAgHIgDAAQgIAAgEACgApnB0IAAgeIgSAeIgKAAIAAguIAKAAIAAAeIASgeIAJAAIAAAugAqYB0IAAgeIgSAeIgJAAIAAguIAJAAIAAAeIASgeIAKAAIAAAugArHB0IAAgTIgSAAIAAATIgJAAIAAguIAJAAIAAATIASAAIAAgTIAJAAIAAAugAsiB0IAAguIAJAAIAAAlIAMAAIAAglIAKAAIAAAlIANAAIAAglIAJAAIAAAugAtkB0IAAgdIgLATIgDAAIgKgTIAAAdIgKAAIAAguIAKAAIALAVIANgVIAJAAIAAAugAx3B0IAAglIgPAAIAAgJIAnAAIAAAJIgPAAIAAAlgAyXB0IAAgeIgSAeIgKAAIAAguIAKAAIAAAeIASgeIAKAAIAAAugA1sB0IAAgTIgRAAIAAATIgKAAIAAguIAKAAIAAATIARAAIAAgTIAJAAIAAAugAwmBSQAAAAAAgBQAAAAgBgBQAAAAAAgBQAAgBAAAAQAAgBAAgBQAAAAAAgBQABAAAAgBQAAAAAAgBQABAAABAAQAAgBABAAQAAAAABAAQAAgBABAAQABAAAAABQABAAAAAAQABAAAAABQABAAAAAAQABABAAAAQAAABABAAQAAABAAAAQAAABAAABQAAAAAAABQAAABAAAAQgBABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAQAAABgBAAQAAAAgBAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBAAgBgBgAp4A+QgDgDgCgEIAGgCIACAEIAFABIADgBQABgBAAAAQAAAAABgBQAAAAAAgBQAAAAAAgBIAGACQgBAEgEADQgDACgEAAQgEAAgDgCgAyoA+QgDgDgCgEIAHgCIACAEIAEABIAEgBQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAAAgBIAGACQgCAEgDADQgDACgFAAQgEAAgDgCgASlAuIAAg+IAJAAIAAAGQADgDADgCQAEgBAEAAQAFAAAEADQAFACADAFQABAGAAAFQAAAHgBAFQgDAFgEADQgFADgFAAQgEAAgEgBIgGgEIAAAXgASxgDQgEADAAAFQAAAGAEAFQADAFAGAAQAFAAADgFQADgEAAgGQAAgGgDgDQgDgFgFAAQgGAAgDAFgAIbAuIAAg+IAJAAIAAAGQADgDAEgCQADgBAFAAQAEAAAFADQAEACADAFQACAGAAAFQAAAHgCAFQgDAFgEADQgEADgGAAQgEAAgDgBIgHgEIAAAXgAImgDQgDADAAAFQAAAGADAFQAEAFAFAAQAGAAADgFQADgEAAgGQAAgGgDgDQgDgFgGAAQgFAAgEAFgAi1AuIAIgUIgRgqIAJAAIAMAeIAMgeIAJAAIgXA+gAUiApIAAgNIgdAAIAAgsIAJAAIAAAjIAQAAIAAgjIAJAAIAAAjIAFAAIAAAWgAtFApIAAgNIgdAAIAAgsIAKAAIAAAjIAPAAIAAgjIAJAAIAAAjIAFAAIAAAWgAPVAlIAAgHIgfAAIAAAHIgJAAIAAgQIAFAAQAGgJAAgMIAAgQIAiAAIAAAlIAFAAIAAAQgAPCAAQAAAIgCAFQgCAGgBACIAUAAIAAgcIgPAAgAFvAlIAAgHIgfAAIAAAHIgJAAIAAgQIAFAAQAGgJAAgMIAAgQIAiAAIAAAlIAFAAIAAAQgAFcAAQAAAIgCAFQgCAGgCACIAVAAIAAgcIgPAAgATbAbQgDgCgCgDQgCgDAAgDQAAgIAFgDQAFgEAFgBIAOAAQgBgJgIAAIgHACIgDAFIgHgFQACgDAFgDQAEgDAHAAQAFAAAEACQADACADAEQACAFAAADIAAAcIgHAAIgBgEQgIAFgHgBQgEAAgEgBgATiAIQgEACAAAFQAAACADACQACADAEAAQADAAADgDQAEgCAAgEIAAgHIgEAAQgGAAgFACgAR8AbQgEgCgCgDQgCgDAAgDQAAgIAFgDQAFgEAGgBIAMAAQABgJgKAAIgGACIgDAFIgHgFQACgDAEgDQAFgDAGAAQAGAAADACQAFACACAEQACAFAAADIAAAcIgHAAIgCgEQgGAFgIgBQgEAAgDgBgASCAIQgEACAAAFQAAACACACQADADAEAAQAEAAADgDQACgCAAgEIAAgHIgCAAQgIAAgEACgARGAcIgCgBIAAgJIABAAIADABQACAAABgFIAAgOIAAgQIAhAAIAAAsIgKAAIAAgjIgNAAIAAAHQAAAOgDAIQgEAGgFAAIgDAAgAPwAZQgFgDgCgFQgDgGAAgGQAAgFADgEQACgGAFgDQAGgDAGAAQAIAAAEAEQAFAEACAFQACAEAAAFIAAADIghAAQAAAFAEADQADADAGAAQADAAADgCQADgBACgCIAHAEQgDAEgFADQgFACgGAAQgGAAgGgDgAP0gFQgEADAAADIAYAAQgBgDgDgDQgDgDgFgBQgFABgDADgAM7AbQgDgCgCgDQgCgDAAgDQAAgIAFgDQAFgEAFgBIAOAAQgBgJgIAAIgGACIgEAFIgHgFQACgDAEgDQAFgDAHAAQAEAAAFACQAEACACAEQACAFAAADIAAAcIgHAAIgBgEQgIAFgHgBQgEAAgEgBgANCAIQgEACAAAFQAAACADACQACADADAAQAFAAACgDQADgCABgEIAAgHIgEAAQgGAAgFACgAKGAZQgEgDgDgFQgDgGAAgGQAAgFADgEQADgGAEgDQAFgDAHAAQAHAAAGAEQAEAEACAFQACAEAAAFIAAADIghAAQABAFACADQAEADAFAAQAEAAADgCQADgBACgCIAHAEQgDAEgFADQgGACgFAAQgHAAgFgDgAKJgFQgCADgBADIAYAAQgBgDgDgDQgDgDgFgBQgFABgEADgAJVAZQgGgDgCgFQgCgGgBgGQABgFACgEQACgGAGgDQAEgDAIAAQAGAAAFADQAFADADAGQACAEAAAFQAAAHgCAFQgDAFgFADQgFADgGAAQgIAAgEgDgAJXgDQgDADAAAFQAAAHADAEQAEAFAGAAQAFAAAEgFQADgEAAgHQAAgFgDgDQgEgFgFAAQgGAAgEAFgAGxAbQAAAAAAgBQgBgBAAAAQAAgBAAAAQgBgBAAAAQAAgBABgBQAAAAAAgBQAAAAABgBQAAAAAAgBQABAAAAgBQABAAAAAAQABAAAAAAQABgBABAAQAAAAABABQABAAAAAAQABAAAAAAQABABAAAAQAAABABAAQAAABAAAAQAAABAAAAQABABAAABQAAAAgBABQAAAAAAABQAAAAAAABQgBABAAAAQAAAAgBABQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAgBAAQAAAAgBAAQAAAAgBAAQAAgBgBAAgAGIAbQgEgCgCgDQgCgDAAgDQAAgIAFgDQAFgEAGgBIAMAAQABgJgKAAIgGACIgDAFIgHgFQACgDAEgDQAFgDAGAAQAGAAADACQAFACACAEQACAFAAADIAAAcIgHAAIgCgEQgGAFgIgBQgEAAgDgBgAGOAIQgEACAAAFQAAACACACQADADADAAQAFAAADgDQACgCAAgEIAAgHIgCAAQgIAAgEACgAEeAZQgFgDgDgFQgDgGAAgGQAAgFADgEQADgGAFgDQAEgDAHAAQAHAAAGADQAFADACAGQACAEABAFQgBAHgCAFQgCAFgFADQgGADgHAAQgHAAgEgDgAEggDQgDADAAAFQAAAHADAEQAEAFAFAAQAHAAADgFQADgEAAgHQAAgFgDgDQgDgFgHAAQgFAAgEAFgACnAaQgFgDgDgFQgCgFAAgGIABgGIABgDIACgDIARgcIALAAIgNAXIADAAQAFAAAEABQAGADACAFQADACAAAGQAAAGgDAFQgCAFgGADQgEACgGAAQgGAAgFgCgACqAAQgEACABAFQgBAFAEAEQADADAFAAQAEAAAEgDQADgEAAgFQAAgFgDgCQgDgCgFAAQgFAAgDACgABNAZQgGgEgDgHQgDgHAAgIQAAgKADgIQADgHAGgEQAGgEAHAAQAIAAAHAEQAFAEADAHQAEAIgBAKQABAIgEAHQgDAHgFAEQgHADgIAAQgHAAgGgDgABSgWQgDADgCAGQgCAFAAAHQAAAEACAFQACAGADADQAEADAEAAQAIAAAEgGQAEgHAAgIQAAgLgEgHQgEgGgIAAQgEAAgEADgAgwAbQgEgCgCgDQgBgDAAgDQAAgIAEgDQAGgEAFgBIANAAQAAgJgJAAIgGACIgEAFIgHgFQACgDAFgDQAFgDAGAAQAFAAAEACQAEACADAEQABAFAAADIAAAcIgHAAIgBgEQgHAFgHgBQgFAAgDgBgAgqAIQgEACAAAFQABACACACQACADAEAAQAEAAADgDQADgCAAgEIAAgHIgDAAQgHAAgFACgAiFAaQgFgDgCgGQgDgFAAgGQAAgGADgFQACgFAFgDQAGgDAGAAQAFAAAFACQAFACADAEIgIAFQgCgDgDgBQgCgBgDAAQgGAAgDAEQgDAEAAAFQAAAHADAEQADAEAGABQADAAACgCQADgBACgCIAHAEQgCAEgFACQgFACgFAAQgGAAgGgCgAk7AbQgDgCgDgDQgCgDAAgDQAAgIAGgDQAEgEAGgBIANAAQAAgJgJAAIgGACIgEAFIgGgFQABgDAFgDQAFgDAGAAQAFAAAEACQAEACACAEQACAFAAADIAAAcIgGAAIgCgEQgHAFgHgBQgEAAgEgBgAk0AIQgFACAAAFQAAACADACQADADADAAQAEAAADgDQADgCAAgEIAAgHIgDAAQgHAAgEACgAmnAbIgIgCIgDgCIAEgIIADABIAFACIAHACQAFAAADgCQADgBABgDQABgDAAgDQAAgFgDgDQgDgBgFAAIgJAAIAAgFIAPgSIgXAAIAAgJIAkAAIAAAFIgPASQAEABAEACQAEADACADQADADAAAGQAAAIgEAEQgEAEgFACQgFACgFAAIgIgBgAn5AZQgFgDgDgFQgDgGAAgGQAAgFADgEQADgGAFgDQAFgDAGAAQAHAAAGADQAFADACAGQADAEAAAFQAAAHgDAFQgCAFgFADQgGADgHAAQgGAAgFgDgAn3gDQgDADAAAFQAAAHADAEQAEAFAFAAQAHAAADgFQADgEAAgHQAAgFgDgDQgDgFgHAAQgFAAgEAFgAqvAaQgFgDgDgGQgDgFAAgGQAAgGADgFQADgFAFgDQAFgDAGAAQAFAAAFACQAFACADAEIgIAFQgCgDgCgBQgDgBgDAAQgFAAgEAEQgDAEAAAFQAAAHADAEQAEAEAFABQADAAADgCQACgBACgCIAHAEQgDAEgEACQgFACgFAAQgGAAgFgCgAwAAbQAAAAAAgBQgBgBAAAAQAAgBAAAAQgBgBAAAAQAAgBABgBQAAAAAAgBQAAAAABgBQAAAAAAgBQABAAAAgBQABAAAAAAQABAAAAAAQABgBABAAQAAAAABABQABAAAAAAQABAAAAAAQABABAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAABAAABQAAAAAAABQAAAAAAABQAAAAAAABQgBABAAAAQAAAAgBABQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAgBAAQAAAAgBAAQAAAAgBAAQAAgBgBAAgAwmAaQgFgDgDgFQgCgFAAgGIABgGIACgDIABgDIASgcIALAAIgOAXIADAAQAGAAAEABQAFADADAFQADACAAAGQAAAGgDAFQgDAFgFADQgEACgHAAQgGAAgFgCgAwjAAQgDACAAAFQAAAFADAEQAEADAEAAQAFAAADgDQADgEABgFQgBgFgDgCQgCgCgGAAQgEAAgEACgAyAAZQgFgEgEgHQgCgHAAgIQAAgKACgIQAEgHAFgEQAHgEAHAAQAIAAAGAEQAFAEADAHQAEAIAAAKQAAAIgEAHQgDAHgFAEQgGADgIAAQgHAAgHgDgAx6gWQgEADgCAGQgBAFAAAHQAAAEABAFQACAGAEADQADADAFAAQAIAAAEgGQADgHAAgIQAAgLgDgHQgEgGgIAAQgFAAgDADgAzLAbQgBAAAAgBQgBgBAAAAQAAgBAAAAQgBgBAAAAQAAgBABgBQAAAAAAgBQAAAAABgBQAAAAABgBQAAAAAAgBQABAAAAAAQABAAAAAAQABgBAAAAQABAAABABQABAAAAAAQABAAAAAAQABABAAAAQAAABABAAQAAABAAAAQAAABAAAAQABABAAABQAAAAgBABQAAAAAAABQAAAAAAABQgBABAAAAQgBAAAAABQgBAAAAAAQgBAAAAAAQgBAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAgBAAAAgA0bAZQgHgEgCgHQgDgHgBgIQABgKADgIQACgHAHgEQAFgEAIAAQAIAAAGAEQAGAEADAHQADAIAAAKQAAAIgDAHQgDAHgGAEQgGADgIAAQgIAAgFgDgA0WgWQgDADgCAGQgCAFAAAHQAAAEACAFQACAGADADQADADAFAAQAHAAAFgGQADgHAAgIQAAgLgDgHQgFgGgHAAQgFAAgDADgA01AbQgBAAAAgBQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBQAAAAAAgBQAAAAABgBQAAAAABgBQAAAAAAgBQABAAAAAAQABAAAAAAQABgBAAAAQABAAABABQABAAAAAAQABAAAAAAQABABAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAABAAABQAAAAAAABQAAAAAAABQAAAAAAABQgBABAAAAQgBAAAAABQgBAAAAAAQgBAAAAAAQgBAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAgBAAAAgA1bAbIgIgCIgEgCIAFgIIACABIAGACIAHACQAEAAADgCQAEgBABgDQABgDAAgDQAAgFgDgDQgDgBgFAAIgJAAIAAgFIAOgSIgWAAIAAgJIAkAAIAAAFIgQASQAFABADACQAEADADADQADADgBAGQAAAIgDAEQgEAEgFACQgGACgEAAIgIgBgAV/AcIAAgOIgIAAIgIAOIgLAAIAJgPQgFgCgBgEQgCgEAAgDQAAgEABgEQACgDADgCQAEgDAFAAIAUAAIAAAsgAVzgHIgDACQgCACAAADQAAACACABIADACIADABIAJAAIAAgOIgJAAgAVTAcIAAgcIgSAcIgKAAIAAgsIAKAAIAAAcIASgcIAJAAIAAAsgAQ0AcIgRgUIAAAUIgJAAIAAgsIAJAAIAAAQIAPgQIALAAIgTAUIAUAYgAN8AcIAAgOIgHAAIgIAOIgLAAIAIgPQgEgCgBgEQgCgEAAgDQAAgEABgEQACgDADgCQAEgDAFAAIAUAAIAAAsgANxgHIgDACQgCACAAADQAAACACABIADACIACABIAJAAIAAgOIgJAAgAMiAcIAAgTIgQAAIAAATIgKAAIAAgsIAKAAIAAARIAQAAIAAgRIAKAAIAAAsgALoAcIAAgjIgOAAIAAgJIAmAAIAAAJIgOAAIAAAjgALKAcIgRgUIAAAUIgJAAIAAgsIAJAAIAAAQIAPgQIALAAIgUAUIAWAYgAIGAcIAAg0IgaAAIAAA0IgKAAIAAg9IAuAAIAAA9gADvAcIAAgsIAfAAIAAAJIgVAAIAAAjgACHAcIAAgvIgLAHIAAgMIARgJIAEAAIAAA9gAAVAcIAAgEIATgYIAHgKQACgDAAgDQAAgEgDgCQgCgDgEAAQgEAAgDADQgDACAAAEQAAAGAEACIgFAHQgEgCgCgEQgCgDAAgGQAAgFACgFQADgDAEgCQAEgDAGAAQAFAAAEADQAFACACADQACAFABAFQgBAIgGAIIgQATIAYAAIAAAJgAhUAcIAAgjIgPAAIAAgJIAmAAIAAAJIgNAAIAAAjgAjiAcIAAgsIAfAAIAAAJIgWAAIAAAjgAkRAcIAAgsIAVAAQAHAAAEAEQAEADAAAHQAAACgBABQgCADgDABQAEABACACQACADAAAFQAAADgCADIgGAEQgDACgFAAgAkJAUIANAAQAEAAACgCQAAAAABgBQAAAAAAgBQABAAAAgBQAAAAAAgBQAAgBAAAAQAAgBgBAAQAAgBAAAAQgBgBAAgBQgCgBgEAAIgNAAgAkJABIAMAAQADAAACgBQAAAAABAAQAAAAAAAAQABAAAAgBQAAAAAAgBQAAgBAAAAQAAgBgBAAQAAgBAAAAQgBgBAAAAQgCgBgDgBIgMAAgAlyAcIAAgvIgLAHIAAgMIARgJIAEAAIAAA9gAoVAcIAAgjIgRAAIAAAjIgKAAIAAgsIAkAAIAAAsgApjAcIAAgvIgKAHIAAgMIAQgJIAFAAIAAA9gArpAcIAAgOIgIAAIgHAOIgLAAIAIgPQgDgCgCgEQgCgEgBgDQAAgEACgEQACgDADgCQAEgDAFAAIAUAAIAAAsgAr0gHIgDACQgCACAAADQAAACACABIADACIACABIAJAAIAAgOIgJAAgAsVAcIAAgcIgSAcIgJAAIAAgsIAJAAIAAAcIASgcIAKAAIAAAsgAt1AcIgRgUIAAAUIgJAAIAAgsIAJAAIAAAQIAPgQIALAAIgTAUIAVAYgAuiAcIgGgPIgHACIgGABIgGgBIgHgCIgFAPIgLAAIAXg9IALAAIAYA9gAu+AEQAEADAFAAQAEAAAGgDIgKgZgAxFAcIAAgvIgMAHIAAgMIARgJIAFAAIAAA9gAy4AcIAAgEIATgYIAIgKQABgDABgDQgBgEgCgCQgDgDgEAAQgEAAgDADQgCACAAAEQAAAGAEACIgFAHQgFgCgCgEQgCgDAAgGQAAgFACgFQADgDAFgCQAEgDAFAAQAGAAAEADQAEACADADQACAFAAAFQAAAIgHAIIgPATIAXAAIAAAJgAziAcIAAgvIgLAHIAAgMIARgJIAFAAIAAA9gA18AcIAAgvIgLAHIAAgMIARgJIAEAAIAAA9gAC7gwIAAhAIAJAAIAAAFQADgDAEgBQADgBAFAAQAEAAAFADQAEACACAFQADAGAAAGQAAAHgDAFQgCAGgEADQgEADgGAAQgEAAgDgBIgHgFIAAAYgADGhkQgCAEAAAGQAAAHACAEQAEAFAFAAQAGAAADgFQADgEAAgGQAAgGgDgFQgDgFgGAAQgFAAgEAFgAmYgwIAAhAIAMAAIAAAEIAGgDIAHgBQAFAAAFADQADADACAGQADAFAAAFQAAAKgFAHQgEAHgKAAIgGgBIgGgEIAAAXgAmLhjQgDAEABAFQgBAGADAEQADAEAEAAQAFAAADgEQACgEAAgGQAAgFgCgEQgDgEgFABQgEgBgDAEgA0ggwIAIgUIgSgsIAKAAIANAfIALgfIAJAAIgXBAgA1ZgwIAAhAIAKAAIAAAFQADgDADgBQADgBAFAAQAFAAAEADQAEACADAFQACAGAAAGQAAAHgCAFQgCAGgEADQgFADgFAAQgFAAgDgBIgGgFIAAAYgA1NhkQgDAEAAAGQAAAHADAEQADAFAGAAQAFAAADgFQADgEABgGQgBgGgDgFQgDgFgFAAQgGAAgDAFgAgBhDIAAgDIgBgDQAAgEACgCQAAgCAEAAQADAAACACQACACAAAEIgBADQAAADgDACIgJAIgAujhCIAAgBIAAgCQgBAAAAAAQAAgBgBAAQAAgBAAAAQAAAAAAgBQAAgBAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAgBABAAQABAAAAAAQABgBAAAAQABAAAAAAQABAAABAAQAAAAABABQAAAAABAAQAAAAABABQAAAAAAABQABAAAAABQAAAAAAABQABABAAAAIgBADIgCADIgKAJgACYhDIgHgEIADgGIAFACIAIACQAEAAADgCQADgCgBgEQAAAAAAgBQAAAAAAgBQAAAAgBgBQAAgBgBAAQgCgCgDAAIgLAAIAAgHIALAAQADAAACgCQAAAAABAAQAAgBAAAAQAAgBAAAAQAAAAAAgBQAAgBAAAAQAAgBAAAAQAAgBgBAAQAAgBAAAAQgCgCgEAAIgIABIgFADIgEgIIAFgBIAGgCIAGAAQAFAAADABIAGAEIABAHQAAAFgDAEQACACABADIABAGQAAAEgBADIgHAGQgDACgGAAQgEAAgFgCgASlhFQgFgDgCgGQgDgFgBgHQABgGADgFQACgFAFgDQAFgDAHAAQAHAAAFADQAFADADAFQACAFAAAGQAAAIgCAEQgDAGgFADQgFADgHAAQgHAAgFgDgASohkQgEAEAAAGQAAAIAEADQADAFAGAAQAGAAAEgFQACgDAAgIQAAgGgCgEQgEgFgGAAQgGAAgDAFgARWhFQgGgDgCgEQgDgFAAgGIABgGIACgGIACgCIARgcIALAAIgOAWIAEAAQAEAAAFACQAFACADAFQADAEAAAHQAAAGgDAFQgDAEgFADQgFADgFAAQgHAAgEgDgARZhgQgEADAAAGQAAAFAEADQACAEAGAAQAEAAAEgEQACgDAAgFQAAgGgCgDQgEgDgEAAQgGAAgCADgAPbhGQgGgDgDgIQgDgHAAgKQAAgKADgHQADgIAGgEQAGgDAHAAQAJAAAFADQAGAEADAIQAEAHgBAKQABAKgEAHQgDAIgGADQgFAEgJAAQgHAAgGgEgAPhh2QgEADgCAFQgCAGAAAGQAAAHACAFQACAFAEADQADAEAEAAQAIgBAEgGQAEgHAAgKQAAgLgEgGQgEgHgIABQgEAAgDADgAOdhGQgGgDgDgIQgDgHAAgKQAAgKADgHQADgIAGgEQAGgDAIAAQAIAAAFADQAGAEADAIQADAHAAAKQAAAKgDAHQgDAIgGADQgFAEgIAAQgIAAgGgEgAOjh2QgEADgCAFQgCAGAAAGQAAAHACAFQACAFAEADQADAEAFAAQAHgBAEgGQAEgHAAgKQAAgLgEgGQgEgHgHABQgFAAgDADgANfhGQgGgDgDgIQgDgHAAgKQAAgKADgHQADgIAGgEQAGgDAIAAQAHAAAGADQAGAEADAIQAEAHAAAKQAAAKgEAHQgDAIgGADQgGAEgHAAQgIAAgGgEgANlh2QgEADgCAFQgCAGAAAGQAAAHACAFQACAFAEADQADAEAFAAQAHgBAEgGQAEgHAAgKQAAgLgEgGQgEgHgHABQgFAAgDADgAMuhDIgIgDIgEgCIAFgIIACABIAGADIAHACQAEAAADgCQAEgCABgDQABgDAAgDQAAgEgDgDQgDgEgFAAIgJAAIAAgEIAOgSIgWAAIAAgJIAkAAIAAAEIgQATQAFAAADADQAEACADAEQADAFgBAGQAAAHgDAFQgEAEgFACQgGACgEAAIgIgBgAH1hFQgFgDgDgGQgDgFAAgHQAAgFADgGQADgFAFgDQAEgDAHAAQAHAAAGADQAEAEACAGQACAFAAAFIAAAEIghAAQAAAEADADQAEAEAFAAQAEgBADgBQADgBABgDIAIAFQgDAEgFACQgGADgFAAQgHAAgEgDgAH3hlQgDADAAAFIAYAAQAAgFgEgDQgDgEgFAAQgFAAgEAEgAFlhFQgFgDgDgGQgCgFAAgHQAAgFACgGQADgFAFgDQAFgDAGAAQAIAAAFADQAEAEACAGQACAFABAFIAAAEIghAAQAAAEADADQADAEAGAAQAEgBADgBQACgBACgDIAHAFQgCAEgGACQgFADgGAAQgGAAgFgDgAFohlQgDADAAAFIAYAAQgBgFgEgDQgCgEgGAAQgEAAgEAEgAD0hFQgFgDgCgGQgDgFAAgHQAAgFADgGQACgFAFgDQAGgDAGAAQAIAAAEADQAFAEACAGQACAFAAAFIAAAEIghAAQABAEADADQADAEAGAAQADgBADgBQADgBABgDIAIAFQgDAEgFACQgFADgGAAQgGAAgGgDgAD4hlQgDADgBAFIAYAAQgBgFgDgDQgDgEgFAAQgFAAgDAEgABqhDQgDgCgDgEQgCgCAAgEQAAgIAGgDQAEgEAGAAIANgBQAAgKgJAAIgGACQgDABgBADIgGgEQABgEAFgDQAFgCAGAAQAFAAAEACQAEABACAEQACAFAAAGIAAAcIgGAAIgCgFQgHAFgHAAQgEAAgEgBgABxhXQgFADAAAEQAAADADACQADACADAAQAEAAADgCQADgCAAgFIAAgHIgDAAQgHAAgEACgAhqhHQgFgEgBgGIgCgIQAAgNAEgIQADgJAIgGQAIgGAOgDIADALIgRAFQgEACgCABIgDAGQAEgEAGAAQAGAAAEAEQAFADADAGQABAEAAAHQABAGgDAFQgDAGgFADQgFADgGAAQgKAAgEgFgAhjhkQgCADgBADIgBAFIABAFQABADACACQACADAFAAQAEAAADgEQADgEAAgFQAAgGgDgEQgDgDgEAAQgFAAgCACgAifhGQgEgDAAgGQAAgIAEgDQAFgEAGAAIAMgCQAAgHgIAAIgEABIgEADIgJgEQADgEAEgDQAFgCAGAAQAFAAAFACQAEACADAFQADAEAAAHIAAAaIgKAAIgBgFQgHAFgHAAQgGAAgFgEgAiThXQgEACAAAEQAAABABAAQAAABAAABQAAAAABABQAAAAABABQACACACAAQAEAAADgCQABgDAAgDIAAgGIgCAAQgGAAgDABgAj4hFQgFgDgCgFQgEgFAAgHQAAgHAEgFQACgGAFgCQAFgDAHAAQAFAAAFACQAFACADADIgKAGIgEgCIgEgBQgEAAgDADQgDAEAAAFQAAAGADAEQADAEAEAAIAEgCIAEgCIAKAGQgDAEgFACQgFACgFAAQgHAAgFgDgAldhFQgFgDgDgFQgDgFAAgIQAAgGADgFQADgGAFgCQAFgDAHAAQAHAAAFADQAFACADAGQACAFAAAGQAAAIgCAFQgDAFgFADQgFADgHAAQgHAAgFgDgAlYhjQgDAEgBAFQABAGADAEQACAEAFAAQAEAAADgEQADgEAAgGQAAgFgDgEQgDgDgEAAQgFAAgCADgAnthFQgFgDgCgFQgDgFAAgHQAAgHADgFQACgGAFgCQAGgDAHAAQAEAAAGACQAEACADADIgKAGIgDgCIgEgBQgFAAgCADQgDAEAAAFQAAAGADAEQACAEAFAAIAEgCIADgCIAKAGQgDAEgEACQgGACgEAAQgHAAgGgDgAoahFQgFgDgDgFQgDgFAAgHQAAgHADgFQADgGAFgCQAGgDAGAAQAFAAAFACQAFACADADIgLAGIgDgCIgEgBQgEAAgDADQgDAEAAAFQAAAGADAEQADAEAEAAIAEgCIADgCIALAGQgDAEgFACQgFACgFAAQgGAAgGgDgApMhFQgFgDgDgFQgDgFAAgIQAAgGADgFQADgGAFgCQAFgDAHAAQAHAAAEADQAGACACAGQADAFAAAGQAAAIgDAFQgCAFgGADQgEADgHAAQgHAAgFgDgApIhjQgCAEAAAFQAAAGACAEQADAEAFAAQAEAAADgEQADgEgBgGQABgFgDgEQgDgDgEAAQgFAAgDADgAsmhGQgHgEgEgHQgEgHAAgKQAAgKAEgHQAEgIAHgEQAGgDAJAAQAIAAAHADQAHAEAEAIQAEAHAAAKQAAAKgEAHQgEAHgHAEQgHAEgIAAQgJAAgGgEgAsgh0QgDADgCAEQgDAFAAAGQAAAGADAFQACAEADADQAFACAEAAQAFAAADgCQAEgDACgEQACgFAAgGQAAgGgCgFQgCgEgEgDQgDgDgFABQgEgBgFADgAwKhGQgGgEgEgHQgEgHAAgKQAAgKAEgHQAEgIAGgEQAHgDAIAAQAHAAAFACQAGADAEAFIgJAEQgDgDgDgBQgDgBgEAAQgFAAgEADQgFACgCAGQgDAFABAHQgBAHADAGQACAEAFADQAEADAFAAQAEAAADgBQADgCADgDIAJAFQgEAFgGACQgGADgGAAQgIAAgHgEgAyUhDQgEgCgCgEQgCgCAAgEQAAgIAFgDQAFgEAGAAIAMgBQABgKgKAAIgGACQgCABgBADIgHgEQACgEAEgDQAFgCAGAAQAGAAADACQAFABACAEQACAFAAAGIAAAcIgHAAIgCgFQgGAFgIAAQgEAAgDgBgAyOhXQgEADAAAEQAAADACACQADACADAAQAFAAADgCQACgCAAgFIAAgHIgCAAQgIAAgEACgATbhCIAAglIgOAAIAAgJIAlAAIAAAJIgOAAIAAAlgAQ1hCIAAgyIgKAHIAAgLIAQgJIAFAAIAAA/gAQVhCIAAgyIgLAHIAAgLIARgJIAFAAIAAA/gAMNhCIAAgyIgLAHIAAgLIARgJIAEAAIAAA/gALVhCIAAgFIATgZIAHgKQACgDAAgDQAAgEgDgDQgDgCgDAAQgEAAgDACQgDADAAAEQAAAFAEACIgFAHQgEgCgCgDQgDgEABgFQgBgGADgEQADgEAEgCQAFgCAFAAQAFAAAEACQAFACACAEQACAEAAAGQAAAIgGAIIgQAVIAXAAIAAAJgAKihCIAeg2IgeAAIAAgJIArAAIAAAEIgfA7gAJxhCIAdg2IgdAAIAAgJIAqAAIAAAEIgfA7gAJQhEQgCgBgBgEIgJgYIAAAWIAFABQAAAAABAAQAAAAAAABQAAAAAAABQAAAAAAABQAAABAAAAQAAABAAAAQAAABAAAAQgBAAAAABIgGABIgFAAIgGgBQAAgBgBAAQAAAAAAgBQAAAAAAgBQgBAAAAgBQABgEAEAAIAAgkQgEAAgBgFIABgCQABgBAAAAQABAAAAgBQABAAABAAQAAAAABAAIAEAAIAEABIACAFIAKAYIAAgVQgHAAAAgFQAAAAAAAAQAAgBAAAAQABgBAAAAQAAAAAAAAQACgCAEAAIAGAAIAGABQAAAAABABQAAAAAAABQAAAAAAABQABAAAAAAQAAAFgFAAIAAAkIAAAEIgCAEIgEABQAAAAgBgBQAAAAgBAAQAAAAAAAAQgBgBAAAAgAHZhCIAAgfIgSAfIgKAAIAAguIAKAAIAAAeIASgeIAJAAIAAAugAGohCIAAgTIgQAAIAAATIgKAAIAAguIAKAAIAAATIAQAAIAAgTIAKAAIAAAugAEehCIAAguIAJAAIAAAlIAMAAIAAglIAJAAIAAAlIANAAIAAglIAKAAIAAAugAAwhCIAAg/IAZAAQAGAAAEACQAEACADAEQADAEAAAFQAAAGgDAEQgDAEgEACQgEADgGAAIgPAAIAAAbgAA6hmIAPAAQAEAAADgDQADgCAAgEQAAgEgDgDQgDgCgEAAIgPAAgAglhPIARgLIgRgMIAAgNIAbAUIAAAIIgbAVgAg8hPIAQgLIgQgMIAAgNIAdAWIAAAEIgdAXgAi3hCIAAgSIgPAAIAAASIgMAAIAAguIAMAAIAAARIAPAAIAAgRIAMAAIAAAugAkXhCIAAgZIgPAZIgMAAIAAguIAMAAIAAAZIAPgZIAMAAIAAAugAm7hCIAAgiIgPAAIAAgMIAqAAIAAAMIgPAAIAAAigApthCIAAglIgKAYIgJAAIgKgYIAAAlIgOAAIAAg/IAOAAIAOAhIAPghIAOAAIAAA/gAq/hZIAAgEIAcgWIAAANIgQAMIAQALIAAANgArUhXIAAgIIAagUIAAANIgQAMIAQALIAAANgAtIhCIgFgOQgHACgEAAQgFAAgGgCIgFAOIgOAAIAWg/IAPAAIAXA/gAtghbQAEACAEAAQADAAAFgCIgIgYgAu3hCIAAgbIgcAAIAAAbIgKAAIAAg/IAKAAIAAAbIAcAAIAAgbIAKAAIAAA/gAwqhCIAAg2IgaAAIAAA2IgKAAIAAg/IAvAAIAAA/gAyuhCIAAglIgRAAIAAAlIgJAAIAAguIAkAAIAAAugAzchCIAAglIgRAAIAAAlIgKAAIAAguIAkAAIAAAugA2HhCIAAg/IAmAAIAAAJIgcAAIAAA2gAJihMQgGgBAAgEIABgCQABgBAEAAIACAAQAEAAACABIAAACQAAAEgGABgAJchfIAAgKQABgDACgCQABgCADAAQADAAADACQABACAAADIAAAKQABAIgIgBQgGABgBgIgAJihoIAAAJQAAAAABABQAAAAAAAAQAAAAAAAAQAAABAAAAQABAAAAgBQAAAAAAAAQAAAAAAAAQAAgBAAAAIAAgJQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAAAgBAAQAAAAAAAAQAAAAAAABQAAAAAAAAQgBABAAAAgAknh4QgDgCgBgFIAHgCIACADIAEABQABAAAAAAQAAAAABAAQAAAAABAAQAAgBABAAQAAAAAAgBQABAAAAAAQAAgBABAAQAAgBAAAAIAGACQgBAFgEACQgDACgFAAQgEAAgEgCg");
	this.shape_127.setTransform(144.2,17.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_127},{t:this.shape_126},{t:this.shape_125},{t:this.shape_124},{t:this.shape_123},{t:this.shape_122},{t:this.shape_121},{t:this.shape_120},{t:this.shape_119},{t:this.shape_118},{t:this.shape_117},{t:this.shape_116},{t:this.shape_115},{t:this.shape_114},{t:this.shape_113},{t:this.shape_112},{t:this.shape_111},{t:this.shape_110},{t:this.shape_109},{t:this.shape_108},{t:this.shape_107},{t:this.shape_106},{t:this.shape_105},{t:this.shape_104},{t:this.shape_103},{t:this.shape_102},{t:this.shape_101},{t:this.shape_100},{t:this.shape_99},{t:this.shape_98},{t:this.shape_97},{t:this.shape_96},{t:this.shape_95},{t:this.shape_94},{t:this.shape_93},{t:this.shape_92},{t:this.shape_91},{t:this.shape_90},{t:this.shape_89},{t:this.shape_88},{t:this.shape_87},{t:this.shape_86},{t:this.shape_85},{t:this.shape_84},{t:this.shape_83},{t:this.shape_82},{t:this.shape_81},{t:this.shape_80},{t:this.shape_79},{t:this.shape_78},{t:this.shape_77},{t:this.shape_76},{t:this.shape_75},{t:this.shape_74},{t:this.shape_73},{t:this.shape_72},{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,4.3,298.5,131);


(lib.Символ13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.cat_cut_02();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,159,146);


(lib.Символ12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.cat_cut_08();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,55,56);


(lib.Символ11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.cat_cut_04();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,42,58);


(lib.Символ9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.logo();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,134,60);


(lib.Символ8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.pattern();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,50,48);


(lib.Символ7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.city();
	this.instance.setTransform(-18,-7,1.184,1.149);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-18,-7,284.2,275.7);


(lib.Символ6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.wall();
	this.instance.setTransform(16,-20,0.859,0.859);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(16,-20,357.4,323.1);


(lib.Символ3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.cat_cut_07();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,159,93);


(lib.Символ21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Символ 22
	this.instance = new lib.Символ22();
	this.instance.setTransform(454.6,258,0.922,0.922,0,0,0,122.1,22.4);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(54).to({_off:false},0).to({x:149.6},9,cjs.Ease.get(1)).wait(30).to({x:-152.3},10,cjs.Ease.get(-1)).wait(1));

	// Символ 20
	this.instance_1 = new lib.Символ20();
	this.instance_1.setTransform(448,252.9,1,1,0,0,0,143,13.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({x:143},9,cjs.Ease.get(1)).wait(30).to({x:-158.9},10,cjs.Ease.get(-1)).to({_off:true},1).wait(54));

	// Символ 19
	this.instance_2 = new lib.Символ19();
	this.instance_2.setTransform(452.7,269.3,0.605,0.605,0,0,0,76.7,14.2);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(5).to({_off:false},0).to({x:147.7},9,cjs.Ease.get(1)).wait(30).to({x:-154.2},10,cjs.Ease.get(-1)).to({_off:true},1).wait(49));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(308.2,246.9,279.7,16.2);


(lib.Символ15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ8();
	this.instance.setTransform(300.4,15.3,0.634,0.634,0,0,180,25.1,24.1);

	this.instance_1 = new lib.Символ8();
	this.instance_1.setTransform(268.9,15.3,0.634,0.634,0,0,180,25,24.1);

	this.instance_2 = new lib.Символ8();
	this.instance_2.setTransform(300.4,45.7,0.634,0.634,0,0,180,25.1,24.1);

	this.instance_3 = new lib.Символ8();
	this.instance_3.setTransform(268.9,45.7,0.634,0.634,0,0,180,25,24.1);

	this.instance_4 = new lib.Символ8();
	this.instance_4.setTransform(237.3,15.3,0.634,0.634,0,0,180,25.1,24.1);

	this.instance_5 = new lib.Символ8();
	this.instance_5.setTransform(205.8,15.3,0.634,0.634,0,0,180,25,24.1);

	this.instance_6 = new lib.Символ8();
	this.instance_6.setTransform(237.3,45.7,0.634,0.634,0,0,180,25.1,24.1);

	this.instance_7 = new lib.Символ8();
	this.instance_7.setTransform(205.8,45.7,0.634,0.634,0,0,180,25,24.1);

	this.instance_8 = new lib.Символ8();
	this.instance_8.setTransform(174,15.3,0.634,0.634,0,0,180,25.1,24.1);

	this.instance_9 = new lib.Символ8();
	this.instance_9.setTransform(142.5,15.3,0.634,0.634,0,0,180,25,24.1);

	this.instance_10 = new lib.Символ8();
	this.instance_10.setTransform(174,45.7,0.634,0.634,0,0,180,25.1,24.1);

	this.instance_11 = new lib.Символ8();
	this.instance_11.setTransform(142.5,45.7,0.634,0.634,0,0,180,25,24.1);

	this.instance_12 = new lib.Символ8();
	this.instance_12.setTransform(111.2,15.3,0.634,0.634,0,0,180,25.1,24.1);

	this.instance_13 = new lib.Символ8();
	this.instance_13.setTransform(79.7,15.3,0.634,0.634,0,0,180,25,24.1);

	this.instance_14 = new lib.Символ8();
	this.instance_14.setTransform(111.2,45.7,0.634,0.634,0,0,180,25.1,24.1);

	this.instance_15 = new lib.Символ8();
	this.instance_15.setTransform(79.7,45.7,0.634,0.634,0,0,180,25,24.1);

	this.instance_16 = new lib.Символ8();
	this.instance_16.setTransform(47.9,15.3,0.634,0.634,0,0,180,25.1,24.1);

	this.instance_17 = new lib.Символ8();
	this.instance_17.setTransform(16.4,15.3,0.634,0.634,0,0,180,25,24.1);

	this.instance_18 = new lib.Символ8();
	this.instance_18.setTransform(47.9,45.7,0.634,0.634,0,0,180,25.1,24.1);

	this.instance_19 = new lib.Символ8();
	this.instance_19.setTransform(16.4,45.7,0.634,0.634,0,0,180,25,24.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_19},{t:this.instance_18},{t:this.instance_17},{t:this.instance_16},{t:this.instance_15},{t:this.instance_14},{t:this.instance_13},{t:this.instance_12},{t:this.instance_11},{t:this.instance_10},{t:this.instance_9},{t:this.instance_8},{t:this.instance_7},{t:this.instance_6},{t:this.instance_5},{t:this.instance_4},{t:this.instance_3},{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(1));

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ak7EwIAApfIJ3AAIAAJfg");
	this.shape.setTransform(147.4,30.4,4.656,1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,316.3,60.8);


(lib.Символ14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ9();
	this.instance.setTransform(0,30,1,1,0,0,0,67,30);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AsuFJIAAqRIZdAAIAAKRg");
	this.shape.setTransform(0,26.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-81.5,-6.9,163,67);


(lib.Символ5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ11();
	this.instance.setTransform(21,29,1,1,0,0,0,21,29);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:-1.8,x:22,y:29.7},14,cjs.Ease.get(-1)).to({rotation:-3.7,x:22.9,y:30.3},15,cjs.Ease.get(1)).to({rotation:-1.8,x:22,y:29.7},15,cjs.Ease.get(-1)).to({rotation:0,x:21,y:29},15,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,42,58);


(lib.Символ4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ12();
	this.instance.setTransform(27.5,28,1,1,0,0,0,27.5,28);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:1,scaleY:1,rotation:-11,x:21.2,y:23.9},12,cjs.Ease.get(-1)).to({scaleX:1,scaleY:1,rotation:-22.2,x:14.9,y:19.7},12,cjs.Ease.get(1)).to({regX:27.4,scaleX:1,scaleY:1,rotation:-11,x:21.2,y:23.9},10,cjs.Ease.get(-1)).to({regX:27.5,scaleX:1,scaleY:1,rotation:0,x:27.5,y:28},10,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,55,56);


(lib.Символ2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ13();
	this.instance.setTransform(79.5,73,1,1,0,0,0,79.5,73);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:-1.5,x:79.6},19,cjs.Ease.get(-1)).to({rotation:-3.2},20,cjs.Ease.get(1)).to({rotation:-1.5},20,cjs.Ease.get(-1)).to({rotation:0,x:79.5},20,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,159,146);


(lib.Символ1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Символ 4
	this.instance = new lib.Символ4();
	this.instance.setTransform(563.6,49.6,0.929,0.929,0,0,0,27.5,28.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Символ 2
	this.instance_1 = new lib.Символ2();
	this.instance_1.setTransform(510.7,-4.4,0.929,0.929,0,0,0,79.5,73);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// Символ 5
	this.instance_2 = new lib.Символ5();
	this.instance_2.setTransform(474.1,75.5,0.929,0.929,0,0,0,21.1,29);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

	// Символ 3
	this.instance_3 = new lib.Символ3();
	this.instance_3.setTransform(541.3,89.9,0.929,0.929,0,0,0,79.5,46.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(436.8,-72.2,178.3,205.2);


(lib.Символ16 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ14();
	this.instance.setTransform(236.1,44.5,1.057,1.057,0,0,0,67,30);

	this.instance_1 = new lib.Символ15();
	this.instance_1.setTransform(284.2,29.7,0.999,0.977,0,0,180,31.7,30.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,315.9,76.2);


(lib.Символ10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Символ 1
	this.instance = new lib.Символ1();
	this.instance.setTransform(-278.7,213.7,0.865,0.865,0,0,0,79.5,73);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regX:79.4,regY:73.1,x:-274.8,y:213.8},39,cjs.Ease.get(-1)).to({regX:79.5,regY:73,x:-270.7,y:213.7},38,cjs.Ease.get(1)).to({regX:79.4,regY:73.1,x:-274.7,y:213.8},38,cjs.Ease.get(-1)).to({regX:79.5,regY:73,x:-278.7,y:213.7},40,cjs.Ease.get(1)).wait(1));

	// Символ 6
	this.instance_1 = new lib.Символ6();
	this.instance_1.setTransform(166,150.1,1,1,0,0,0,166,150.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({x:172.1},39,cjs.Ease.get(-1)).to({x:178},38,cjs.Ease.get(1)).to({x:172.2},38,cjs.Ease.get(-1)).to({x:166},40,cjs.Ease.get(1)).wait(1));

	// Символ 7
	this.instance_2 = new lib.Символ7();
	this.instance_2.setTransform(170.5,120.5,1,1,0,0,0,120,120);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({x:160.4},39,cjs.Ease.get(-1)).to({x:150.5},38,cjs.Ease.get(1)).to({x:160.3},38,cjs.Ease.get(-1)).to({x:170.5},40,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(16,-20,357.4,323.1);


// stage content:



(lib.dom_cat300300 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FF3300").ss(1,1,1).p("A3W3WMAutAAAMAAAAutMgutAAAg");
	this.shape.setTransform(150,150);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Символ 9
	this.instance = new lib.Символ16();
	this.instance.setTransform(143.2,24.1,1,1,0,0,0,157.9,38.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 9
	this.instance_1 = new lib.Символ17();
	this.instance_1.setTransform(150.8,284.4,1,1,0,0,0,149.3,16.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// Слой 8
	this.instance_2 = new lib.Символ21();
	this.instance_2.setTransform(351.6,129.9,1,1,0,0,0,345.6,138.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

	// Слой 3
	this.instance_3 = new lib.Символ10();
	this.instance_3.setTransform(-3.7,127.7,0.93,0.93,0,0,0,26.6,150);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(135.3,119.5,608.6,433.5);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;